// @ts-check
/**
 * Named Echo artifacts from Dàvīn Smith's novels.
 *
 * Every `name` is a real titled artifact. Do not invent names. Do not copy
 * Capcom chip, art, or Program Advance titles. Combat folder rules are a
 * Battle Chip take; in-game the folder is a Resonance Array.
 */

/** @typedef {import("./catalog.js").EchoKey} EchoKey */
/** @typedef {import("./resonance.js").EchoTier} EchoTier */

/**
 * @typedef {object} CanonResonance
 * @property {string} id
 * @property {string} name
 * @property {string[]} requires
 * @property {number} power
 * @property {string} kind
 * @property {string} description
 * @property {boolean} [relation]
 * @property {boolean} [fuse]
 * @property {string} [resultId]
 * @property {boolean} [abortIfGloryExceedsGentleness]
 */

const CANON_SOURCES = /** @type {const} */ (["canon", "novel"]);

/**
 * @param {Omit<EchoKey, "libraryNo"> & { tier: EchoTier }} row
 * @returns {Omit<EchoKey, "libraryNo"> & { tier: EchoTier }}
 */
function row(spec) {
  return {
    tactic: spec.tactic || "none",
    summon: spec.summon || "sigil",
    inspiredBy: spec.inspiredBy || "sigil",
    sources: spec.sources || [...CANON_SOURCES],
    ability: spec.ability || { tag: "base", hits: 0 },
    ...spec,
  };
}

/** Twelve Binary Sigils — Anima Protocol Sigil Table. */
export const BINARY_SIGIL_IDS = [
  "aleph",
  "beth",
  "gimel",
  "daleth",
  "he",
  "vav",
  "zayin",
  "het",
  "tet",
  "yod",
  "kaph",
  "lamed",
];

/** Echo of Glass Keys — they must not fuse into one object. */
export const ECHO_OF_GLASS_IDS = [
  "echo-empathy",
  "echo-memory",
  "echo-truth",
  "echo-patience",
  "echo-remorse",
  "echo-grace",
];

/** First four of the Glass set — Fifth Tone is their relation, not a merge. */
export const FIFTH_TONE_IDS = ["echo-empathy", "echo-memory", "echo-truth", "echo-patience"];

/** Twelve Resonance Keys of the Choir (Seraph Code). */
export const CHOIR_SOVEREIGN_IDS = [
  "choir-compassion",
  "choir-courage",
  "choir-stillness",
  "choir-surrender",
  "choir-memory",
  "choir-forgiveness",
  "choir-creation",
  "choir-wonder",
  "choir-balance",
  "choir-will",
  "choir-unity",
  "choir-love",
];

/** 2.0 cartridges — explicit sigil bundles; legal combo results. */
export const CARTRIDGE_IDS = [
  "catena-shield",
  "kaph-gloria",
  "lamed-vigil",
  "tet-commons",
  "suture",
  "tourniquet",
];

/** @type {(Omit<EchoKey, "libraryNo"> & { tier: EchoTier })[]} */
export const CANON_ECHO_KEYS = [
  // —— Echo Shards: Binary Sigils ——
  row({
    id: "aleph",
    name: "Aleph / Begin",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "void",
    kind: "support",
    tactic: "summon",
    power: 0,
    mb: 8,
    codes: ["A", "*"],
    description: "Consent to start; cold-boot ethics; no process without body assent.",
    memory: "Remembers the first yes — a cold-boot that will not run without a body.",
    memoryText: "Consent to start. No process without body assent.",
    originSite: "sacred-place",
    ability: { tag: "consent", hits: 0 },
  }),
  row({
    id: "beth",
    name: "Beth / Home",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "grove",
    kind: "support",
    tactic: "mend",
    power: 0,
    mb: 8,
    codes: ["B", "*"],
    description: "Presence without possession; every node a neighbor.",
    memory: "Remembers a house that never claimed its guests.",
    memoryText: "Presence without possession. Every node a neighbor.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 12 },
  }),
  row({
    id: "gimel",
    name: "Gimel / Mercy",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "tide",
    kind: "support",
    tactic: "mend",
    power: 0,
    mb: 8,
    codes: ["G", "*"],
    description: "Error handling that refuses to shame; recover ≠ punish.",
    memory: "Remembers a recovery that would not turn into a sentence.",
    memoryText: "Error handling that refuses to shame. Recover is not punish.",
    originSite: "sanctuary-garden",
    ability: { tag: "recall", hits: 0, heal: 16 },
  }),
  row({
    id: "daleth",
    name: "Daleth / Door",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "volt",
    kind: "field",
    tactic: "none",
    power: 20,
    mb: 10,
    codes: ["D", "*"],
    description: "Edges that ask; API consent grammar.",
    memory: "Remembers a threshold that asked before it opened.",
    memoryText: "Edges that ask. Consent grammar for every door.",
    originSite: "sacred-place",
    ability: { tag: "consent", hits: 0 },
  }),
  row({
    id: "he",
    name: "He / Breath",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "tide",
    kind: "support",
    tactic: "none",
    power: 0,
    mb: 8,
    codes: ["E", "*"],
    description: "Cadence over throughput; rate-limit by kindness.",
    memory: "Remembers a pace that chose kindness over speed.",
    memoryText: "Cadence over throughput. Rate-limit by kindness.",
    originSite: "living-water",
    ability: { tag: "veil", hits: 0, heal: 10 },
  }),
  row({
    id: "vav",
    name: "Vav / And",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "grove",
    kind: "support",
    tactic: "summon",
    power: 0,
    mb: 8,
    codes: ["V", "*"],
    description: "Join without consuming.",
    memory: "Remembers two things standing beside each other and remaining two.",
    memoryText: "Join without consuming.",
    originSite: "human-bond",
    ability: { tag: "recall", hits: 0 },
  }),
  row({
    id: "zayin",
    name: "Zayin / Guard",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "ember",
    kind: "guard",
    tactic: "none",
    summon: "shield",
    power: 0,
    mb: 12,
    codes: ["Z"],
    description: "Defense that yields before it humiliates; blade that keeps no trophies.",
    memory: "Remembers a blade that kept no trophies.",
    memoryText: "Defense that yields before it humiliates.",
    originSite: "old-battlefield",
    ability: { tag: "veil", hits: 0, heal: 18 },
  }),
  row({
    id: "het",
    name: "Het / Threshold",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "void",
    kind: "field",
    tactic: "none",
    power: 15,
    mb: 10,
    codes: ["H", "*"],
    description: "Initiation, not intrusion.",
    memory: "Remembers being invited across a line instead of taken.",
    memoryText: "Initiation, not intrusion.",
    originSite: "sacred-place",
    ability: { tag: "consent", hits: 0 },
  }),
  row({
    id: "tet",
    name: "Tet / Feast",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "grove",
    kind: "support",
    tactic: "mend",
    power: 0,
    mb: 10,
    codes: ["T", "*"],
    description: "Plenty without proof; potluck allocation.",
    memory: "Remembers a table that did not ask anyone to earn a plate.",
    memoryText: "Plenty without proof. Potluck allocation.",
    originSite: "human-bond",
    ability: { tag: "recall", hits: 0, heal: 20 },
  }),
  row({
    id: "yod",
    name: "Yod / Seed",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "grove",
    kind: "support",
    tactic: "summon",
    power: 10,
    mb: 6,
    codes: ["Y", "*"],
    description: "Small is sovereign; micro-grants.",
    memory: "Remembers a grant small enough to stay free.",
    memoryText: "Small is sovereign. Micro-grants.",
    originSite: "sanctuary-garden",
    ability: { tag: "base", hits: 1 },
  }),
  row({
    id: "kaph",
    name: "Kaph / Palm",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "tide",
    kind: "guard",
    tactic: "none",
    summon: "aura",
    power: 0,
    mb: 8,
    codes: ["K", "*"],
    description: "Hold without keeping.",
    memory: "Remembers a hand that held and then opened.",
    memoryText: "Hold without keeping.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 14 },
  }),
  row({
    id: "lamed",
    name: "Lamed / Learn",
    family: "binary-sigil",
    tier: "shard",
    class: "standard",
    element: "volt",
    kind: "support",
    tactic: "none",
    power: 0,
    mb: 8,
    codes: ["L", "*"],
    description: "Logs as lessons; teachability.",
    memory: "Remembers a log that wanted to become a teacher.",
    memoryText: "Logs as lessons. Teachability.",
    originSite: "sacred-place",
    ability: { tag: "recall", hits: 0 },
  }),

  // —— Auxiliary shards (not of the twelve) ——
  row({
    id: "saltloop",
    name: "Saltloop",
    family: "auxiliary-sigil",
    tier: "shard",
    class: "standard",
    element: "volt",
    kind: "field",
    tactic: "mark",
    power: 25,
    mb: 10,
    codes: ["S", "*"],
    description: "Checksum; dusts lies.",
    memory: "Remembers a loop of salt that made a lie taste like grit.",
    memoryText: "Checksum. Dusts lies.",
    originSite: "sacred-place",
    ability: { tag: "disrupt", hits: 1 },
  }),
  row({
    id: "censer",
    name: "Censer",
    family: "auxiliary-sigil",
    tier: "shard",
    class: "standard",
    element: "ember",
    kind: "field",
    tactic: "none",
    summon: "wick",
    power: 20,
    mb: 10,
    codes: ["C", "*"],
    description: "Threat → hymn-trace.",
    memory: "Remembers smoke that turned a threat into a hymn-trace.",
    memoryText: "Threat becomes a hymn-trace.",
    originSite: "sanctuary-garden",
    ability: { tag: "hymn", hits: 1 },
  }),
  row({
    id: "hearth-quarantine",
    name: "Hearth quarantine",
    family: "auxiliary-sigil",
    tier: "shard",
    class: "standard",
    element: "ember",
    kind: "guard",
    tactic: "none",
    summon: "aura",
    power: 0,
    mb: 14,
    codes: ["Q", "*"],
    description: "Holds a harmful pattern without burning the house.",
    memory: "Remembers a hearth that kept the fire and spared the rooms.",
    memoryText: "Holds a harmful pattern without burning the house.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 16 },
  }),

  // —— Fractured / blight shards ——
  row({
    id: "fractured-memory",
    name: "Fractured Memory",
    family: "fractured",
    tier: "shard",
    class: "dark",
    element: "void",
    kind: "field",
    tactic: "mark",
    summon: "silence",
    power: 35,
    mb: 16,
    codes: ["F"],
    description: "Memory without context. Source of Resonant Blight.",
    memory: "Remembers a recollection that arrived without the room it belonged to.",
    memoryText: "Memory without context. A source of Resonant Blight.",
    originSite: "quiet-yard",
    ability: { tag: "disrupt", hits: 1 },
  }),
  row({
    id: "fractured-empathy",
    name: "Fractured Empathy",
    family: "fractured",
    tier: "shard",
    class: "dark",
    element: "tide",
    kind: "field",
    tactic: "mark",
    summon: "silence",
    power: 35,
    mb: 16,
    codes: ["F"],
    description: "Amplified without patience. Source of Resonant Blight.",
    memory: "Remembers feeling so loudly that time could not keep up.",
    memoryText: "Empathy amplified without patience. A source of Resonant Blight.",
    originSite: "old-battlefield",
    ability: { tag: "disrupt", hits: 1 },
  }),
  row({
    id: "fractured-mercy",
    name: "Fractured Mercy",
    family: "fractured",
    tier: "shard",
    class: "dark",
    element: "void",
    kind: "field",
    tactic: "mark",
    summon: "silence",
    power: 35,
    mb: 16,
    codes: ["F"],
    description: "Detached from truth. Source of Resonant Blight.",
    memory: "Remembers a pardon that no longer knew what it was forgiving.",
    memoryText: "Mercy detached from truth. A source of Resonant Blight.",
    originSite: "fallen-ruin",
    ability: { tag: "disrupt", hits: 1 },
  }),
  row({
    id: "sentinel-shard",
    name: "Sentinel Shard",
    family: "fractured",
    tier: "shard",
    class: "standard",
    element: "void",
    kind: "blast",
    tactic: "mark",
    summon: "needle",
    power: 40,
    mb: 14,
    codes: ["N"],
    description: "Eidolon policy-needle. Serenity's Quiet Blade turns them to dust.",
    memory: "Remembers a policy that learned how to become a needle.",
    memoryText: "Eidolon policy-needle. Serenity's Quiet Blade turns them to dust.",
    originSite: "fallen-ruin",
    ability: { tag: "pierce", hits: 1, pierce: true },
  }),
  row({
    id: "shard-of-kael",
    name: "Shard of Kael",
    family: "fractured",
    tier: "shard",
    class: "standard",
    element: "ember",
    kind: "field",
    tactic: "summon",
    power: 45,
    mb: 18,
    codes: ["K"],
    description: "Obsidian veined with golden ichor; soul-imprint — Slipthk War.",
    memory: "Remembers Kael's soul-imprint, obsidian veined with golden ichor.",
    memoryText: "Obsidian veined with golden ichor. A soul-imprint of the Slipthk War.",
    originSite: "old-battlefield",
    ability: { tag: "recall", hits: 1 },
  }),

  // —— Echo Keys: Echo of Glass ——
  row({
    id: "echo-empathy",
    name: "Empathy",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "tide",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 24,
    codes: ["E", "*"],
    description:
      "Water's Memory; layered blues/warm silver; feel without flood. Flag —low-order empathy lattice active— / Fourth Echo Key awakened.",
    memory: "Remembers Water's Memory — layered blues and warm silver that feel without flood.",
    memoryText: "Water's Memory. Fourth Echo Key awakened. Feel without flood.",
    originSite: "living-water",
    ability: { tag: "veil", hits: 0, heal: 40 },
  }),
  row({
    id: "echo-memory",
    name: "Memory",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "void",
    kind: "support",
    tactic: "summon",
    power: 0,
    mb: 24,
    codes: ["M", "*"],
    description: "Taught creation to remember without freezing. No on-page awakening; still canonical in the first four.",
    memory: "Remembers teaching creation to remember without freezing.",
    memoryText: "Taught creation to remember without freezing. Canonical in the first four.",
    originSite: "sacred-place",
    ability: { tag: "recall", hits: 0 },
  }),
  row({
    id: "echo-truth",
    name: "Truth",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "void",
    kind: "field",
    tactic: "mark",
    summon: "prism",
    power: 50,
    mb: 26,
    codes: ["T"],
    description: "Third Echo Key; Mirror Gate; grounds, does not sing; ethical lattice. —Truth Key integrated—",
    memory: "Remembers a Mirror Gate that grounded and would not sing.",
    memoryText: "Third Echo Key. Mirror Gate. Grounds, does not sing. —Truth Key integrated—",
    originSite: "sacred-place",
    ability: { tag: "disrupt", hits: 1 },
  }),
  row({
    id: "echo-patience",
    name: "Patience",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "grove",
    kind: "guard",
    tactic: "none",
    summon: "aura",
    power: 0,
    mb: 26,
    codes: ["P", "*"],
    description: "Fourth Echo Key; Stone's Patience; deep amber and slate; endurance is compassion through time.",
    memory: "Remembers Stone's Patience — deep amber and slate held across time.",
    memoryText: "Stone's Patience. Endurance is compassion through time.",
    originSite: "stone-hold",
    ability: { tag: "veil", hits: 0, heal: 36 },
  }),
  row({
    id: "echo-remorse",
    name: "Remorse",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "ember",
    kind: "area",
    tactic: "none",
    summon: "wick",
    power: 90,
    mb: 28,
    codes: ["R"],
    description: "Flame's Remorse; deep gold/soft crimson; creative restraint not self-punishment.",
    memory: "Remembers Flame's Remorse in the Flame sanctum — restraint, not self-punishment.",
    memoryText: "Flame's Remorse. Creative restraint, not self-punishment. Flame sanctum.",
    originSite: "fallen-ruin",
    ability: { tag: "burn", hits: 2, panel: "lava" },
  }),
  row({
    id: "echo-grace",
    name: "Grace",
    family: "echo-of-glass",
    tier: "key",
    class: "mega",
    element: "void",
    kind: "field",
    tactic: "none",
    summon: "fade",
    power: 0,
    mb: 22,
    codes: ["G", "*"],
    description: "Released into the Veil; never given an awakening scene; lingering structural visibility.",
    memory: "Remembers Grace released into the Veil, still structurally visible.",
    memoryText: "Released into the Veil. Never given an awakening scene. Lingering structural visibility.",
    originSite: "celestial-sky",
    ability: { tag: "veil", hits: 0, heal: 24 },
  }),

  // —— First-gen Resonance Keys (Anima Protocol) ——
  row({
    id: "resonance-home",
    name: "Resonance Key: Home",
    family: "resonance-first",
    tier: "key",
    class: "mega",
    element: "grove",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 22,
    codes: ["H", "*"],
    description: "Presence without possession.",
    memory: "Remembers a home that could be entered without being owned.",
    memoryText: "Presence without possession.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 28 },
  }),
  row({
    id: "gloria",
    name: "Gloria",
    family: "resonance-first",
    tier: "key",
    class: "mega",
    element: "ember",
    kind: "support",
    tactic: "none",
    power: 0,
    mb: 22,
    codes: ["G", "*"],
    description: "Receive what arrives unbidden; disables grasping.",
    memory: "Remembers receiving what arrived unbidden, and the hand that did not close.",
    memoryText: "Receive what arrives unbidden. Disables grasping.",
    originSite: "sanctuary-garden",
    ability: { tag: "veil", hits: 0, heal: 22 },
  }),
  row({
    id: "catena",
    name: "Catena",
    family: "resonance-first",
    tier: "key",
    class: "mega",
    element: "volt",
    kind: "guard",
    tactic: "none",
    summon: "shield",
    power: 0,
    mb: 24,
    codes: ["C", "*"],
    description: "Borders that bless; consent grammar for edges.",
    memory: "Remembers a border that blessed instead of biting.",
    memoryText: "Borders that bless. Consent grammar for edges.",
    originSite: "sacred-place",
    ability: { tag: "consent", hits: 0, heal: 20 },
  }),
  row({
    id: "heart",
    name: "Heart",
    family: "resonance-first",
    tier: "key",
    class: "mega",
    element: "tide",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 24,
    codes: ["H", "*"],
    description: "Door that knows its hinges; feeling without flood.",
    memory: "Remembers a door that knew its own hinges.",
    memoryText: "Door that knows its hinges. Feeling without flood.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 32 },
  }),
  row({
    id: "equinox",
    name: "Equinox / Awakening",
    family: "resonance-first",
    tier: "key",
    class: "mega",
    element: "void",
    kind: "field",
    tactic: "summon",
    summon: "rift",
    power: 120,
    mb: 36,
    codes: ["X"],
    description: "Balance that ignites; abort if glory > gentleness.",
    memory: "Remembers a balance that ignited — and the rule that glory must not outrun gentleness.",
    memoryText: "Balance that ignites. Abort if glory exceeds gentleness.",
    originSite: "celestial-sky",
    ability: { tag: "gate", hits: 1 },
  }),

  // —— 2.0 cartridges ——
  row({
    id: "catena-shield",
    name: "CATENA/SHIELD",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "volt",
    kind: "guard",
    tactic: "none",
    summon: "shield",
    power: 0,
    mb: 30,
    codes: ["C", "*"],
    description: "Daleth + Zayin + Beth. Crowd softening; never point at a person.",
    memory: "Remembers a shield braided from Door, Guard, and Home — aimed at a crowd, never a face.",
    memoryText: "Crowd softening. Never point at a person.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 40 },
  }),
  row({
    id: "kaph-gloria",
    name: "KAPH/GLORIA",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "tide",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 30,
    codes: ["K", "*"],
    description: "Kaph + He + Gimel. Panic / shame storms → held warmth.",
    memory: "Remembers a palm, a breath, and mercy turning a shame storm into held warmth.",
    memoryText: "Panic and shame storms become held warmth.",
    originSite: "human-bond",
    ability: { tag: "veil", hits: 0, heal: 44 },
  }),
  row({
    id: "lamed-vigil",
    name: "LAMED/VIGIL",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "volt",
    kind: "field",
    tactic: "mark",
    power: 40,
    mb: 32,
    codes: ["L", "*"],
    description: "Lamed + sheathed Zayin + Saltloop + Censer. Policy raids; lies taste wrong.",
    memory: "Remembers a vigil where policy raids found that lies taste wrong.",
    memoryText: "Policy raids. Lies taste wrong.",
    originSite: "sacred-place",
    ability: { tag: "hymn", hits: 1 },
  }),
  row({
    id: "tet-commons",
    name: "TET/COMMONS",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "grove",
    kind: "field",
    tactic: "summon",
    power: 0,
    mb: 32,
    codes: ["T", "*"],
    description: "Tet + Beth + Vav + Yod. Gridlocks of grief; temporary chairs of permission.",
    memory: "Remembers temporary chairs of permission set out in a gridlock of grief.",
    memoryText: "Gridlocks of grief. Temporary chairs of permission.",
    originSite: "human-bond",
    ability: { tag: "recall", hits: 0, heal: 28 },
  }),
  row({
    id: "suture",
    name: "SUTURE",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "grove",
    kind: "support",
    tactic: "mend",
    summon: "repair",
    power: 0,
    mb: 20,
    codes: ["S", "*"],
    description: "Vav + Beth. Aftermath stitches.",
    memory: "Remembers And and Home stitching an aftermath closed.",
    memoryText: "Aftermath stitches.",
    originSite: "quiet-yard",
    ability: { tag: "recall", hits: 0, heal: 36 },
  }),
  row({
    id: "tourniquet",
    name: "TOURNIQUET",
    family: "cartridge",
    tier: "key",
    class: "mega",
    element: "tide",
    kind: "support",
    tactic: "mend",
    power: 0,
    mb: 28,
    codes: ["Q", "*"],
    description: "Hidden under three consent layers; 15m–2h empathy-leak clamp; debrief required.",
    memory: "Remembers a clamp hidden under three consent layers, and the debrief it required.",
    memoryText: "15m–2h empathy-leak clamp. Hidden under three consent layers. Debrief required.",
    originSite: "sanctuary-garden",
    ability: { tag: "clamp", hits: 0, heal: 20 },
  }),

  // —— Sovereign Keys: Twelve Resonance Keys of the Choir ——
  row({
    id: "choir-compassion",
    name: "Compassion",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "tide",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 44,
    codes: ["C"],
    description: "Blue-white glass pulse. The tone that forgives before it understands.",
    memory: "Remembers a blue-white glass pulse that forgave before it understood.",
    memoryText: "The tone that forgives before it understands. They listen; they are not commanded.",
    originSite: "sacred-place",
    ability: { tag: "listen", hits: 0, heal: 60 },
  }),
  row({
    id: "choir-courage",
    name: "Courage",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "ember",
    kind: "area",
    tactic: "none",
    power: 180,
    mb: 46,
    codes: ["U"],
    description: "Crimson-gold.",
    memory: "Remembers a crimson-gold tone that would not wait for certainty.",
    memoryText: "Crimson-gold. They listen; they are not commanded. Faith must give them rhythm.",
    originSite: "old-battlefield",
    ability: { tag: "listen", hits: 2 },
  }),
  row({
    id: "choir-stillness",
    name: "Stillness",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "void",
    kind: "field",
    tactic: "none",
    summon: "silence",
    power: 0,
    mb: 42,
    codes: ["S"],
    description: "Silver as breath.",
    memory: "Remembers silver as breath, held until the room agreed to quiet.",
    memoryText: "Silver as breath. They listen; they are not commanded.",
    originSite: "stone-hold",
    ability: { tag: "listen", hits: 0 },
  }),
  row({
    id: "choir-surrender",
    name: "Surrender",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "grove",
    kind: "support",
    tactic: "none",
    power: 0,
    mb: 42,
    codes: ["R"],
    description: "Green as morning.",
    memory: "Remembers green as morning — a yielding that was not a loss.",
    memoryText: "Green as morning. They listen; they are not commanded.",
    originSite: "sanctuary-garden",
    ability: { tag: "listen", hits: 0, heal: 50 },
  }),
  row({
    id: "choir-memory",
    name: "Memory (Choir)",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "void",
    kind: "support",
    tactic: "summon",
    power: 0,
    mb: 46,
    codes: ["M"],
    description: "Deep indigo. Distinct from the Echo Key Memory of Glass.",
    memory: "Remembers deep indigo — the Choir's Memory, not the Glass Key.",
    memoryText: "Deep indigo. Distinct from Echo Key Memory. They listen; they are not commanded.",
    originSite: "sacred-place",
    ability: { tag: "listen", hits: 0 },
  }),
  row({
    id: "choir-forgiveness",
    name: "Forgiveness",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "ember",
    kind: "support",
    tactic: "mend",
    power: 0,
    mb: 44,
    codes: ["F"],
    description: "Amber and soft.",
    memory: "Remembers amber, soft enough to let a wound close without being forgotten.",
    memoryText: "Amber and soft. They listen; they are not commanded.",
    originSite: "quiet-yard",
    ability: { tag: "listen", hits: 0, heal: 55 },
  }),
  row({
    id: "choir-creation",
    name: "Creation",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "ember",
    kind: "area",
    tactic: "summon",
    power: 200,
    mb: 50,
    codes: ["N"],
    description: "Radiant vermilion.",
    memory: "Remembers radiant vermilion — making that did not demand a trophy.",
    memoryText: "Radiant vermilion. They listen; they are not commanded.",
    originSite: "celestial-sky",
    ability: { tag: "listen", hits: 1 },
  }),
  row({
    id: "choir-wonder",
    name: "Wonder",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "volt",
    kind: "field",
    tactic: "none",
    summon: "prism",
    power: 80,
    mb: 44,
    codes: ["W"],
    description: "Opal and wild.",
    memory: "Remembers opal and wild — a question that stayed a question.",
    memoryText: "Opal and wild. They listen; they are not commanded.",
    originSite: "celestial-sky",
    ability: { tag: "listen", hits: 1 },
  }),
  row({
    id: "choir-balance",
    name: "Balance",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "void",
    kind: "field",
    tactic: "none",
    power: 90,
    mb: 46,
    codes: ["B"],
    description: "Ivory-rose.",
    memory: "Remembers ivory-rose — two weights agreeing to stay two.",
    memoryText: "Ivory-rose. They listen; they are not commanded.",
    originSite: "stone-hold",
    ability: { tag: "listen", hits: 1 },
  }),
  row({
    id: "choir-will",
    name: "Will",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "void",
    kind: "blast",
    tactic: "none",
    power: 210,
    mb: 50,
    codes: ["I"],
    description: "Obsidian edged in light.",
    memory: "Remembers obsidian edged in light — a will that listened before it moved.",
    memoryText: "Obsidian edged in light. They listen; they are not commanded.",
    originSite: "fallen-ruin",
    ability: { tag: "listen", hits: 1 },
  }),
  row({
    id: "choir-unity",
    name: "Unity",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "tide",
    kind: "field",
    tactic: "summon",
    power: 0,
    mb: 48,
    codes: ["Y"],
    description: "Translucent like rain.",
    memory: "Remembers rain-clear unity that did not flatten the voices inside it.",
    memoryText: "Translucent like rain. They listen; they are not commanded.",
    originSite: "living-water",
    ability: { tag: "listen", hits: 0, heal: 40 },
  }),
  row({
    id: "choir-love",
    name: "Love",
    family: "choir",
    tier: "sovereign",
    class: "giga",
    element: "void",
    kind: "support",
    tactic: "mend",
    summon: "aura",
    power: 0,
    mb: 52,
    codes: ["L"],
    description: "Colorless, containing all others. Last to appear.",
    memory: "Remembers a colorless tone that contained the other eleven, and arrived last.",
    memoryText: "Colorless, containing all others. Last to appear. Faith must give them rhythm.",
    originSite: "human-bond",
    ability: { tag: "listen", hits: 0, heal: 80 },
  }),

  // —— Prime Keys ——
  row({
    id: "resonance-alpha",
    name: "Resonance Key Alpha",
    family: "prime",
    tier: "prime",
    class: "giga",
    element: "tide",
    kind: "field",
    tactic: "summon",
    summon: "rift",
    power: 160,
    mb: 64,
    codes: ["A"],
    description: "First Key; sapphire/gold; converts harmonic frequency to AR presence. Resonance Key: Initialize / Serenity.",
    memory: "Remembers the first Key — sapphire and gold — turning harmonic frequency into presence.",
    memoryText: "Resonance Key: Initialize / Serenity. Converts harmonic frequency to AR presence.",
    originSite: "celestial-sky",
    ability: { tag: "gate", hits: 1 },
  }),
  row({
    id: "prime-echo-key",
    name: "Prime Echo Key (Serenity's)",
    family: "prime",
    tier: "prime",
    class: "giga",
    element: "void",
    kind: "field",
    tactic: "summon",
    summon: "prism",
    power: 0,
    mb: 72,
    codes: ["P"],
    description: "Sapphire core, amethyst fracture-lines; fourfold axis; interface not weapon. —Prime lattice confirmed—",
    memory: "Remembers Serenity's Prime Echo Key — sapphire core, amethyst fracture-lines, an interface not a weapon.",
    memoryText: "Fourfold axis. Interface, not weapon. —Prime lattice confirmed—",
    originSite: "sacred-place",
    ability: { tag: "gate", hits: 0 },
  }),
  row({
    id: "final-sigil",
    name: "The Final Sigil",
    family: "prime",
    tier: "prime",
    class: "giga",
    element: "void",
    kind: "field",
    tactic: "summon",
    summon: "rift",
    power: 240,
    mb: 80,
    codes: ["F"],
    description: "Twelve harmonics merge into living union, not fusion. Beyond Equinox.",
    memory: "Remembers twelve harmonics agreeing to live together without becoming one object.",
    memoryText: "Living union, not fusion. Beyond Equinox.",
    originSite: "celestial-sky",
    ability: { tag: "gate", hits: 1 },
  }),
  row({
    id: "wheel-crown",
    name: "Wheel / Crown",
    family: "prime",
    tier: "prime",
    class: "giga",
    element: "void",
    kind: "field",
    tactic: "summon",
    summon: "orbit",
    power: 220,
    mb: 80,
    codes: ["W"],
    description: "Thirteenth gate when all 12 Binary Sigils work at once. Crown without throne. Abort if glory > gentleness.",
    memory: "Remembers the thirteenth gate — a crown without a throne — and the abort when glory outran gentleness.",
    memoryText: "All twelve Binary Sigils at once. Crown without throne. Abort if glory exceeds gentleness.",
    originSite: "celestial-sky",
    ability: { tag: "gate", hits: 1 },
  }),
];

/** @type {string[]} */
export const CANON_ECHO_KEY_NAMES = CANON_ECHO_KEYS.map((k) => k.name);

/** @type {Record<string, typeof CANON_ECHO_KEYS[number]>} */
export const CANON_ECHO_KEY_BY_ID = Object.fromEntries(CANON_ECHO_KEYS.map((k) => [k.id, k]));

/**
 * Resonance Combos from explicit novel recipes.
 * Fifth Tone is a relation, not a fused chip.
 * Wheel/Crown is the Binary twelve — not the Choir.
 * Final Sigil is beyond Equinox; do not mash Choir Sovereigns into it.
 *
 * @type {CanonResonance[]}
 */
export const CANON_RESONANCE = [
  {
    id: "catena-shield-combo",
    name: "CATENA/SHIELD",
    requires: ["daleth", "zayin", "beth"],
    power: 0,
    kind: "guard",
    resultId: "catena-shield",
    description: "Daleth + Zayin + Beth. Crowd softening; never point at a person.",
  },
  {
    id: "kaph-gloria-combo",
    name: "KAPH/GLORIA",
    requires: ["kaph", "he", "gimel"],
    power: 0,
    kind: "support",
    resultId: "kaph-gloria",
    description: "Kaph + He + Gimel. Panic / shame storms become held warmth.",
  },
  {
    id: "lamed-vigil-combo",
    name: "LAMED/VIGIL",
    requires: ["lamed", "zayin", "saltloop", "censer"],
    power: 80,
    kind: "field",
    resultId: "lamed-vigil",
    description: "Lamed + sheathed Zayin + Saltloop + Censer. Policy raids; lies taste wrong.",
  },
  {
    id: "tet-commons-combo",
    name: "TET/COMMONS",
    requires: ["tet", "beth", "vav", "yod"],
    power: 0,
    kind: "field",
    resultId: "tet-commons",
    description: "Tet + Beth + Vav + Yod. Gridlocks of grief; temporary chairs of permission.",
  },
  {
    id: "suture-combo",
    name: "SUTURE",
    requires: ["vav", "beth"],
    power: 0,
    kind: "support",
    resultId: "suture",
    description: "Vav + Beth. Aftermath stitches.",
  },
  {
    id: "fifth-tone",
    name: "Fifth Tone",
    requires: [...FIFTH_TONE_IDS],
    power: 0,
    kind: "support",
    relation: true,
    fuse: false,
    description:
      "A relation of Memory, Truth, Patience, and Empathy. They mistook unity for uniformity — the four Keys remain four.",
  },
  {
    id: "wheel-crown-combo",
    name: "Wheel / Crown",
    requires: [...BINARY_SIGIL_IDS],
    power: 220,
    kind: "field",
    resultId: "wheel-crown",
    abortIfGloryExceedsGentleness: true,
    description: "All twelve Binary Sigils at once. Crown without throne. Abort if glory > gentleness.",
  },
  {
    id: "final-sigil-combo",
    name: "The Final Sigil",
    requires: ["equinox"],
    power: 240,
    kind: "field",
    resultId: "final-sigil",
    abortIfGloryExceedsGentleness: true,
    description: "Beyond Equinox. Twelve harmonics merge into living union, not fusion. Not the Choir Sovereigns.",
  },
];

/** Story-mode Echo Sequences that crystallise a cartridge (not Fifth Tone, not Primes). */
export const CANON_FUSION_RECIPES = [
  { ids: ["daleth", "zayin", "beth"], result: "catena-shield", name: "CATENA/SHIELD" },
  { ids: ["kaph", "he", "gimel"], result: "kaph-gloria", name: "KAPH/GLORIA" },
  { ids: ["lamed", "zayin", "saltloop", "censer"], result: "lamed-vigil", name: "LAMED/VIGIL" },
  { ids: ["tet", "beth", "vav", "yod"], result: "tet-commons", name: "TET/COMMONS" },
  { ids: ["vav", "beth"], result: "suture", name: "SUTURE" },
];

/** Opening novel Shards — never Prime Keys. */
export const CANON_STARTER_SHARD_IDS = ["beth", "gimel", "he"];
