// @ts-check
/**
 * Eighty Echo Key families. Each family expands into 10 distinct keys
 * (base / high / apex / ember / tide / volt / grove / star / noise / shade).
 * Inspired by BN1–6 chip families and Star Force card families; names are original.
 */

/**
 * @typedef {"blast"|"sword"|"area"|"heal"|"guard"|"field"|"support"} EchoKind
 * @typedef {"none"|"blade"|"gale"|"mark"|"shatter"|"summon"|"mend"} EchoTactic
 * @typedef {"cannon"|"spreader"|"bomb"|"sword"|"wave"|"tower"|"quake"|"fist"|"dash"|"howitzer"|"arrow"|"homing"|"sheet"|"gaia"|"orb"|"orbit"|"gyre"|"coil"|"drain"|"aura"|"panel"|"hammer"|"shield"|"mend"|"steal"|"field"|"escape"|"silence"|"repair"|"chrono"|"rain"|"mine"|"seek"|"remote"|"lockon"|"wick"|"idol"|"cube"|"buster"|"gauge"|"fade"|"wrap"|"sigil"|"prism"|"gravity"|"rift"|"plasma"|"upper"|"needle"|"fruit"|"jet"|"magnum"|"brother"|"combo"|"noise"|"tribe"|"star"|"meteor"|"satellite"|"bond"} EchoSummon
 */

/**
 * @typedef {object} EchoFamilyDef
 * @property {string} id
 * @property {string} label
 * @property {string} inspiredBy
 * @property {string[]} sources
 * @property {EchoKind} kind
 * @property {EchoTactic} tactic
 * @property {EchoSummon} summon
 * @property {number} basePower
 * @property {string} memory
 * @property {string} [baseName]
 * @property {string[]} [names]
 */

/** @type {EchoFamilyDef[]} */
export const ECHO_FAMILIES = [
  // —— BN1 core (40) ——
  {
    id: "pulse",
    label: "Pulse",
    inspiredBy: "cannon",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "blast",
    tactic: "none",
    summon: "cannon",
    basePower: 40,
    memory: "Remembers the first clean shot — a barrel of light on the forearm.",
    names: [
      "Pulse Emitter",
      "High Pulse",
      "Apex Pulse",
      "Cinder Barrel",
      "Tide Bore",
      "Volt Lance",
      "Grove Shot",
      "Star Pulse",
      "Noise Cannon",
      "Shade Bore",
    ],
  },
  {
    id: "halo",
    label: "Halo",
    inspiredBy: "spreader",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "spreader",
    basePower: 30,
    memory: "Remembers a shot that refuses to stop at the first body.",
    names: [
      "Halo Burst",
      "Cross Halo",
      "Apex Halo",
      "Cinder Ring",
      "Tide Halo",
      "Volt Halo",
      "Grove Halo",
      "Star Spreader",
      "Noise Petal",
      "Shade Ring",
    ],
  },
  {
    id: "seed",
    label: "Seed",
    inspiredBy: "bomb",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "area",
    tactic: "none",
    summon: "bomb",
    basePower: 50,
    memory: "Remembers a thrown spark that blooms three panels deep.",
    names: [
      "Ember Seed",
      "Twin Seed",
      "Cross Seed",
      "Cinder Bloom",
      "Tide Seed",
      "Volt Seed",
      "Grove Seed",
      "Star Seed",
      "Noise Burst",
      "Shade Seed",
    ],
  },
  {
    id: "phantom",
    label: "Phantom",
    inspiredBy: "sword",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "sword",
    tactic: "blade",
    summon: "sword",
    basePower: 80,
    memory: "Remembers a weightless edge — glass-steel, no scabbard.",
    names: [
      "Phantom Edge",
      "Wide Phantom",
      "Long Phantom",
      "Cinder Saber",
      "Tide Saber",
      "Volt Saber",
      "Grove Saber",
      "Star Edge",
      "Noise Blade",
      "Shade Murasa",
    ],
  },
  {
    id: "debt",
    label: "Debt",
    inspiredBy: "muramasa",
    sources: ["BN1", "BN3", "BN4", "BN5", "BN6"],
    kind: "sword",
    tactic: "blade",
    summon: "sword",
    basePower: 10,
    memory: "Remembers every wound already taken and turns it into a cut.",
  },
  {
    id: "tremor",
    label: "Tremor",
    inspiredBy: "shockwave",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "shatter",
    summon: "wave",
    basePower: 60,
    memory: "Remembers a ground-wave that rides one row to the far wall.",
  },
  {
    id: "spire",
    label: "Spire",
    inspiredBy: "tower",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5"],
    kind: "area",
    tactic: "none",
    summon: "tower",
    basePower: 70,
    memory: "Remembers a pillar that can be steered up and down a column.",
  },
  {
    id: "fault",
    label: "Fault",
    inspiredBy: "quake",
    sources: ["BN1", "BN2", "BN3"],
    kind: "area",
    tactic: "shatter",
    summon: "quake",
    basePower: 55,
    memory: "Remembers a thrown stone that cracks the landing panel.",
  },
  {
    id: "geist",
    label: "Geist",
    inspiredBy: "punch",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "sword",
    tactic: "shatter",
    summon: "fist",
    basePower: 70,
    memory: "Remembers a point-blank fist that breaks guards and cubes.",
  },
  {
    id: "afterimage",
    label: "Afterimage",
    inspiredBy: "dash",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "sword",
    tactic: "gale",
    summon: "dash",
    basePower: 65,
    memory: "Remembers a rush down the row — everything in the path folds.",
  },
  {
    id: "breaker",
    label: "Breaker",
    inspiredBy: "howitzer",
    sources: ["BN1", "BN2"],
    kind: "area",
    tactic: "shatter",
    summon: "howitzer",
    basePower: 90,
    memory: "Remembers a heavy shell that unmakes the panel it lands on.",
  },
  {
    id: "gleam",
    label: "Gleam",
    inspiredBy: "arrow",
    sources: ["BN1", "BN2", "BN3"],
    kind: "blast",
    tactic: "mark",
    summon: "arrow",
    basePower: 25,
    memory: "Remembers a three-shot burst of piercing needles.",
  },
  {
    id: "wisp",
    label: "Wisp",
    inspiredBy: "ratton",
    sources: ["BN1", "BN2", "BN3"],
    kind: "blast",
    tactic: "mark",
    summon: "homing",
    basePower: 45,
    memory: "Remembers a missile that turns once toward whoever it wants.",
  },
  {
    id: "sheet",
    label: "Sheet",
    inspiredBy: "row-wave",
    sources: ["BN1", "BN2", "BN3", "SF1"],
    kind: "area",
    tactic: "gale",
    summon: "sheet",
    basePower: 50,
    memory: "Remembers a three-row wave that sweeps the enemy field.",
  },
  {
    id: "rolling",
    label: "Rolling",
    inspiredBy: "gaia",
    sources: ["BN1", "BN2", "BN3"],
    kind: "area",
    tactic: "shatter",
    summon: "gaia",
    basePower: 75,
    memory: "Remembers a rolling three-column explosion.",
  },
  {
    id: "spark",
    label: "Spark",
    inspiredBy: "thunder",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "orb",
    basePower: 40,
    memory: "Remembers a slow lightning orb that rolls the row.",
  },
  {
    id: "orbit",
    label: "Orbit",
    inspiredBy: "ringzap",
    sources: ["BN1", "BN2"],
    kind: "area",
    tactic: "none",
    summon: "orbit",
    basePower: 35,
    memory: "Remembers lightning that circles the Anima once, twice, thrice.",
  },
  {
    id: "gyre",
    label: "Gyre",
    inspiredBy: "tornado",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "area",
    tactic: "gale",
    summon: "gyre",
    basePower: 20,
    memory: "Remembers a stationary twister that hits again and again.",
  },
  {
    id: "coil",
    label: "Coil",
    inspiredBy: "snake",
    sources: ["BN1", "BN2"],
    kind: "blast",
    tactic: "mark",
    summon: "coil",
    basePower: 40,
    memory: "Remembers a squirming line that crawls toward the virus.",
  },
  {
    id: "siphon",
    label: "Siphon",
    inspiredBy: "drain",
    sources: ["BN1", "BN2", "BN3"],
    kind: "sword",
    tactic: "mend",
    summon: "drain",
    basePower: 40,
    memory: "Remembers a charge-in-place that steals HP from the far side.",
  },
  {
    id: "ignition",
    label: "Ignition",
    inspiredBy: "bodyburn",
    sources: ["BN1", "BN2"],
    kind: "area",
    tactic: "none",
    summon: "aura",
    basePower: 55,
    memory: "Remembers adjacent panels catching pale fire.",
  },
  {
    id: "unmake",
    label: "Unmake",
    inspiredBy: "xpanel",
    sources: ["BN1", "BN2", "BN3"],
    kind: "field",
    tactic: "shatter",
    summon: "panel",
    basePower: 0,
    memory: "Remembers deleting a panel — or a whole column — into a hole.",
  },
  {
    id: "mallet",
    label: "Mallet",
    inspiredBy: "hammer",
    sources: ["BN1", "BN2"],
    kind: "sword",
    tactic: "shatter",
    summon: "hammer",
    basePower: 85,
    memory: "Remembers a short-range smash that breaks obstacles.",
  },
  {
    id: "metveil",
    label: "Metveil",
    inspiredBy: "guard",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "guard",
    tactic: "none",
    summon: "shield",
    basePower: 0,
    memory: "Remembers a helmet-parry — one hit turned aside.",
  },
  {
    id: "mend",
    label: "Mend",
    inspiredBy: "recovery",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1", "SF2", "SF3"],
    kind: "heal",
    tactic: "mend",
    summon: "mend",
    basePower: 30,
    memory: "Remembers a pulse of HP returning to the vessel.",
  },
  {
    id: "claim",
    label: "Claim",
    inspiredBy: "steal",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "field",
    tactic: "none",
    summon: "steal",
    basePower: 0,
    memory: "Remembers taking the left column of the enemy area.",
  },
  {
    id: "fracture",
    label: "Fracture",
    inspiredBy: "geddon",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "field",
    tactic: "shatter",
    summon: "field",
    basePower: 0,
    memory: "Remembers every panel cracking — or empty ones falling into holes.",
  },
  {
    id: "jackout",
    label: "Jackout",
    inspiredBy: "escape",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "support",
    tactic: "none",
    summon: "escape",
    basePower: 0,
    memory: "Remembers the jack-out hymn for fights that are not worth the HP.",
  },
  {
    id: "silence",
    label: "Silence",
    inspiredBy: "interrupt",
    sources: ["BN1", "BN2", "BN3"],
    kind: "support",
    tactic: "none",
    summon: "silence",
    basePower: 0,
    memory: "Remembers shredding the enemy's queued weapon data.",
  },
  {
    id: "restore",
    label: "Restore",
    inspiredBy: "repair",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "field",
    tactic: "mend",
    summon: "repair",
    basePower: 0,
    memory: "Remembers putting panels back under the Anima's feet.",
  },
  {
    id: "chrono",
    label: "Chrono",
    inspiredBy: "timebomb",
    sources: ["BN1", "BN2", "BN3"],
    kind: "area",
    tactic: "none",
    summon: "chrono",
    basePower: 80,
    memory: "Remembers a countdown placed in the enemy area.",
  },
  {
    id: "rainveil",
    label: "Rainveil",
    inspiredBy: "cloud",
    sources: ["BN1", "BN2"],
    kind: "area",
    tactic: "none",
    summon: "rain",
    basePower: 45,
    memory: "Remembers rain that sweeps up and down one column.",
  },
  {
    id: "hiddenmine",
    label: "Hiddenmine",
    inspiredBy: "mine",
    sources: ["BN1", "BN2", "BN3"],
    kind: "area",
    tactic: "mark",
    summon: "mine",
    basePower: 70,
    memory: "Remembers a mine that waits on an enemy panel.",
  },
  {
    id: "seekcharge",
    label: "Seekcharge",
    inspiredBy: "dynamite",
    sources: ["BN1", "BN2"],
    kind: "blast",
    tactic: "mark",
    summon: "seek",
    basePower: 60,
    memory: "Remembers a charge that hunts right, then diagonal, then vertical.",
  },
  {
    id: "remotegeist",
    label: "Remotegeist",
    inspiredBy: "remobit",
    sources: ["BN1", "BN2"],
    kind: "blast",
    tactic: "mark",
    summon: "remote",
    basePower: 50,
    memory: "Remembers a remote smasher the operator used to steer.",
  },
  {
    id: "tracesat",
    label: "Tracesat",
    inspiredBy: "lockon",
    sources: ["BN1", "BN2", "SF1", "SF2", "SF3"],
    kind: "blast",
    tactic: "mark",
    summon: "lockon",
    basePower: 35,
    memory: "Remembers an orbiting satellite that fires on its own.",
  },
  {
    id: "lifewick",
    label: "Lifewick",
    inspiredBy: "candle",
    sources: ["BN1", "BN2"],
    kind: "heal",
    tactic: "mend",
    summon: "wick",
    basePower: 15,
    memory: "Remembers a wick that ticks HP until someone snuffs it.",
  },
  {
    id: "wither",
    label: "Wither",
    inspiredBy: "anubis",
    sources: ["BN1", "BN2", "BN3"],
    kind: "area",
    tactic: "summon",
    summon: "idol",
    basePower: 20,
    memory: "Remembers a statue that steadily drains the far side.",
  },
  {
    id: "solid",
    label: "Solid",
    inspiredBy: "cube",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "field",
    tactic: "summon",
    summon: "cube",
    basePower: 0,
    memory: "Remembers ice that melts and rock that asks to be broken.",
  },
  {
    id: "fade",
    label: "Fade",
    inspiredBy: "invis",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "support",
    tactic: "none",
    summon: "fade",
    basePower: 0,
    memory: "Remembers vanishing until the next strike — or until stillness.",
  },

  // —— BN2–6 (25) ——
  {
    id: "needleburst",
    label: "Needleburst",
    inspiredBy: "vulcan",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "cannon",
    basePower: 15,
    memory: "Remembers a machine-gun of light needles.",
  },
  {
    id: "aethersail",
    label: "Aethersail",
    inspiredBy: "airshot",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "gale",
    summon: "cannon",
    basePower: 20,
    memory: "Remembers a cheap wind poke that shoves the target back.",
  },
  {
    id: "returnarc",
    label: "Returnarc",
    inspiredBy: "yoyo",
    sources: ["BN2", "BN3", "BN4"],
    kind: "blast",
    tactic: "gale",
    summon: "orbit",
    basePower: 40,
    memory: "Remembers a returning arc that hits going and coming.",
  },
  {
    id: "windpush",
    label: "Windpush",
    inspiredBy: "wind",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "field",
    tactic: "gale",
    summon: "sheet",
    basePower: 10,
    memory: "Remembers a gust that slides units one panel.",
  },
  {
    id: "fanlift",
    label: "Fanlift",
    inspiredBy: "wind",
    sources: ["BN2", "BN3", "BN4"],
    kind: "field",
    tactic: "gale",
    summon: "sheet",
    basePower: 0,
    memory: "Remembers a fan planted on a panel, blowing the whole row.",
  },
  {
    id: "siegepulse",
    label: "Siegepulse",
    inspiredBy: "tankcannon",
    sources: ["BN6"],
    kind: "blast",
    tactic: "shatter",
    summon: "howitzer",
    basePower: 100,
    memory: "Remembers a heavy cannon with splash on the hit panel.",
  },
  {
    id: "counterhymn",
    label: "Counterhymn",
    inspiredBy: "anti",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "support",
    tactic: "none",
    summon: "silence",
    basePower: 0,
    memory: "Remembers a trap that answers an element, a summon, a heal, or a hit.",
  },
  {
    id: "varblade",
    label: "Varblade",
    inspiredBy: "varsword",
    sources: ["BN3", "BN4", "BN5", "BN6"],
    kind: "sword",
    tactic: "blade",
    summon: "sword",
    basePower: 90,
    memory: "Remembers a blade whose cut-shape the operator writes in the air.",
  },
  {
    id: "stepcut",
    label: "Stepcut",
    inspiredBy: "varsword",
    sources: ["BN3", "BN4", "BN5", "BN6"],
    kind: "sword",
    tactic: "blade",
    summon: "dash",
    basePower: 70,
    memory: "Remembers stepping down the row, slashing each panel.",
  },
  {
    id: "lavaspout",
    label: "Lavaspout",
    inspiredBy: "element-guns",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "cannon",
    basePower: 70,
    memory: "Remembers a magma barrel that leaves the panel burning.",
  },
  {
    id: "woodpowder",
    label: "Woodpowder",
    inspiredBy: "element-guns",
    sources: ["BN2", "BN3", "BN4", "BN5"],
    kind: "area",
    tactic: "none",
    summon: "bomb",
    basePower: 55,
    memory: "Remembers a cloud of seed-dust that clings to grass.",
  },
  {
    id: "elecreel",
    label: "Elecreel",
    inspiredBy: "element-guns",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "coil",
    basePower: 50,
    memory: "Remembers a living wire that snaps toward aqua and metal.",
  },
  {
    id: "heatshot",
    label: "Heatshot",
    inspiredBy: "element-guns",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "blast",
    tactic: "none",
    summon: "cannon",
    basePower: 45,
    memory: "Remembers a compact fire round that ignites wood.",
  },
  {
    id: "panelgrab",
    label: "Panelgrab",
    inspiredBy: "panelgrab",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6", "SF1"],
    kind: "field",
    tactic: "none",
    summon: "steal",
    basePower: 0,
    memory: "Remembers claiming one more panel of the enemy stage.",
  },
  {
    id: "fullcust",
    label: "Fullcust",
    inspiredBy: "fullcust",
    sources: ["BN3", "BN4", "BN5", "BN6"],
    kind: "support",
    tactic: "none",
    summon: "gauge",
    basePower: 0,
    memory: "Remembers the Custom Gauge leaping full in one breath.",
  },
  {
    id: "atkplus",
    label: "Atkplus",
    inspiredBy: "plus",
    sources: ["BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "support",
    tactic: "none",
    summon: "sigil",
    basePower: 10,
    memory: "Remembers a plus-sign branded onto the next strike.",
  },
  {
    id: "beastfang",
    label: "Beastfang",
    inspiredBy: "cross",
    sources: ["BN6"],
    kind: "sword",
    tactic: "blade",
    summon: "sword",
    basePower: 110,
    memory: "Remembers a timed beast window — claws instead of a blade.",
  },
  {
    id: "crossheat",
    label: "Crossheat",
    inspiredBy: "cross",
    sources: ["BN6"],
    kind: "blast",
    tactic: "none",
    summon: "cannon",
    basePower: 85,
    memory: "Remembers the Heat Cross — a charged fire arm.",
  },
  {
    id: "crossslash",
    label: "Crossslash",
    inspiredBy: "cross",
    sources: ["BN6"],
    kind: "sword",
    tactic: "blade",
    summon: "sword",
    basePower: 95,
    memory: "Remembers the Slash Cross — a column cut that steps forward.",
  },
  {
    id: "taglink",
    label: "Taglink",
    inspiredBy: "tag",
    sources: ["BN6"],
    kind: "support",
    tactic: "none",
    summon: "brother",
    basePower: 0,
    memory: "Remembers two Folders sharing one slot.",
  },
  {
    id: "cybreath",
    label: "Cybreath",
    inspiredBy: "cross",
    sources: ["BN6"],
    kind: "area",
    tactic: "none",
    summon: "gaia",
    basePower: 140,
    memory: "Remembers a cybeast exhalation that paints the enemy field.",
  },
  {
    id: "whiteslot",
    label: "Whiteslot",
    inspiredBy: "white-capsule",
    sources: ["BN3"],
    kind: "support",
    tactic: "none",
    summon: "sigil",
    basePower: 0,
    memory: "Remembers a white capsule that rewrites how the next key lands.",
  },
  {
    id: "doublesoul",
    label: "Doublesoul",
    inspiredBy: "soul",
    sources: ["BN4", "BN5"],
    kind: "support",
    tactic: "none",
    summon: "bond",
    basePower: 0,
    memory: "Remembers wearing another being's element for one Custom turn.",
  },
  {
    id: "busterweave",
    label: "Busterweave",
    inspiredBy: "buster-mod",
    sources: ["BN1", "BN2", "BN3"],
    kind: "support",
    tactic: "none",
    summon: "buster",
    basePower: 40,
    memory: "Remembers one Custom turn of Guard, Seed, Edge, or Geist on the hand-cannon.",
  },
  {
    id: "tempo",
    label: "Tempo",
    inspiredBy: "fullcust",
    sources: ["BN1", "BN2", "BN3", "BN4", "BN5", "BN6"],
    kind: "support",
    tactic: "none",
    summon: "gauge",
    basePower: 0,
    memory: "Remembers slowing or speeding the Custom Gauge for both sides.",
  },

  // —— Star Force (15) ——
  {
    id: "plasmagun",
    label: "Plasmagun",
    inspiredBy: "plasma",
    sources: ["SF1", "SF2", "SF3"],
    kind: "blast",
    tactic: "mark",
    summon: "plasma",
    basePower: 50,
    memory: "Remembers a lock-on plasma burst — Star Force's first gun.",
  },
  {
    id: "heatupper",
    label: "Heatupper",
    inspiredBy: "heat-upper",
    sources: ["SF1", "SF2", "SF3"],
    kind: "sword",
    tactic: "shatter",
    summon: "upper",
    basePower: 80,
    memory: "Remembers a rising fire punch that lifts the locked target.",
  },
  {
    id: "iceneedle",
    label: "Iceneedle",
    inspiredBy: "ice-needle",
    sources: ["SF1", "SF2", "SF3"],
    kind: "blast",
    tactic: "mark",
    summon: "needle",
    basePower: 45,
    memory: "Remembers aqua needles pinning a locked panel.",
  },
  {
    id: "poisonfruit",
    label: "Poisonfruit",
    inspiredBy: "poison-fruit",
    sources: ["SF1", "SF2"],
    kind: "area",
    tactic: "mark",
    summon: "fruit",
    basePower: 20,
    memory: "Remembers a fruit that ticks HP off whoever locked it.",
  },
  {
    id: "jetstrike",
    label: "Jetstrike",
    inspiredBy: "jet",
    sources: ["SF1", "SF2", "SF3"],
    kind: "sword",
    tactic: "gale",
    summon: "jet",
    basePower: 75,
    memory: "Remembers rushing the lock-on row until something yields.",
  },
  {
    id: "widewave",
    label: "Widewave",
    inspiredBy: "wide-wave",
    sources: ["SF1", "SF2", "SF3"],
    kind: "area",
    tactic: "gale",
    summon: "sheet",
    basePower: 60,
    memory: "Remembers a three-row wave from a smaller, lock-on field.",
  },
  {
    id: "magnumlock",
    label: "Magnumlock",
    inspiredBy: "magnum",
    sources: ["SF1", "SF2", "SF3"],
    kind: "blast",
    tactic: "shatter",
    summon: "magnum",
    basePower: 110,
    memory: "Remembers a heavy lock-on shot that ignores thin shields.",
  },
  {
    id: "brotherlink",
    label: "Brotherlink",
    inspiredBy: "brother",
    sources: ["SF1", "SF2", "SF3"],
    kind: "support",
    tactic: "none",
    summon: "brother",
    basePower: 0,
    memory: "Remembers a friend contributing one extra key to the draw.",
  },
  {
    id: "bestchain",
    label: "Bestchain",
    inspiredBy: "best-combo",
    sources: ["SF1", "SF2", "SF3"],
    kind: "area",
    tactic: "none",
    summon: "combo",
    basePower: 120,
    memory: "Remembers three matching cards becoming one named finisher.",
  },
  {
    id: "noiseflare",
    label: "Noiseflare",
    inspiredBy: "noise",
    sources: ["SF2"],
    kind: "area",
    tactic: "none",
    summon: "noise",
    basePower: 90,
    memory: "Remembers EM noise remixing the next hand.",
  },
  {
    id: "tribeon",
    label: "Tribeon",
    inspiredBy: "tribe",
    sources: ["SF3"],
    kind: "support",
    tactic: "none",
    summon: "tribe",
    basePower: 0,
    memory: "Remembers a tribe card rewriting the next Custom.",
  },
  {
    id: "stellarlock",
    label: "Stellarlock",
    inspiredBy: "star-force",
    sources: ["SF1", "SF2", "SF3"],
    kind: "blast",
    tactic: "mark",
    summon: "star",
    basePower: 100,
    memory: "Remembers the Star Force lock — version-exclusive starlight.",
  },
  {
    id: "meteorgate",
    label: "Meteorgate",
    inspiredBy: "meteor-g",
    sources: ["SF2", "SF3"],
    kind: "area",
    tactic: "none",
    summon: "meteor",
    basePower: 150,
    memory: "Remembers a sky-fall that blankets the locked field.",
  },
  {
    id: "satflare",
    label: "Satflare",
    inspiredBy: "satellite",
    sources: ["SF1", "SF2", "SF3"],
    kind: "area",
    tactic: "none",
    summon: "satellite",
    basePower: 80,
    memory: "Remembers a satellite-colored flare — fire, aqua, elec, or wood.",
  },
  {
    id: "geoforce",
    label: "Geoforce",
    inspiredBy: "geo-bond",
    sources: ["SF1", "SF2", "SF3"],
    kind: "support",
    tactic: "summon",
    summon: "bond",
    basePower: 0,
    memory: "Remembers the operator and the vessel becoming one wave.",
  },
];

export const VARIANT_SLOTS = [
  { id: "base", class: "standard", elementFrom: "void", ability: "base", powerMul: 1, mb: 8, hits: 1 },
  { id: "high", class: "standard", elementFrom: "void", ability: "pierce", powerMul: 1.7, mb: 22, hits: 1 },
  { id: "apex", class: "standard", elementFrom: "void", ability: "heavy", powerMul: 2.4, mb: 38, hits: 1 },
  { id: "ember", class: "standard", elementFrom: "ember", ability: "burn", powerMul: 1.5, mb: 16, hits: 1 },
  { id: "tide", class: "standard", elementFrom: "tide", ability: "push", powerMul: 1.5, mb: 16, hits: 1 },
  { id: "volt", class: "standard", elementFrom: "volt", ability: "chain", powerMul: 1.5, mb: 16, hits: 1 },
  { id: "grove", class: "standard", elementFrom: "grove", ability: "root", powerMul: 1.5, mb: 16, hits: 1 },
  { id: "star", class: "star", elementFrom: "void", ability: "lockon", powerMul: 2.2, mb: 48, hits: 1 },
  { id: "noise", class: "mega", elementFrom: "void", ability: "multihit", powerMul: 1.8, mb: 56, hits: 5 },
  { id: "shade", class: "dark", elementFrom: "void", ability: "echo-debt", powerMul: 3.0, mb: 74, hits: 1 },
];

export const GIGA_FAMILY_IDS = [
  "cybreath",
  "meteorgate",
  "stellarlock",
  "bestchain",
  "debt",
  "beastfang",
  "geoforce",
  "doublesoul",
];

const DEFAULT_PREFIXES = [
  "",
  "High ",
  "Apex ",
  "Cinder ",
  "Tide ",
  "Volt ",
  "Grove ",
  "Star ",
  "Noise ",
  "Shade ",
];

/**
 * @param {EchoFamilyDef} family
 * @param {number} slotIndex
 */
export function variantName(family, slotIndex) {
  if (family.names?.[slotIndex]) return family.names[slotIndex];
  return `${DEFAULT_PREFIXES[slotIndex]}${family.label}`;
}

export function familyIds() {
  return ECHO_FAMILIES.map((f) => f.id);
}
