import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-[100dvh] bg-background">
      {/* Header */}
      <div className="border-b border-primary/20 bg-black/60 backdrop-blur-md px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center gap-4">
          <Link to="/" className="text-primary/40 hover:text-primary transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="font-mono text-primary glow-text tracking-[0.2em] uppercase text-lg">Disclaimer</h1>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12 pb-24">
        <div className="space-y-8 font-mono text-sm text-primary/70 leading-relaxed">
          
          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">General Disclaimer</h2>
            <p>This application is provided on an "as-is" basis. While we strive to provide accurate and helpful information, we make no warranties regarding the completeness, accuracy, or reliability of any content generated by our AI systems.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">AI-Generated Content</h2>
            <p>The responses generated by our AI are based on machine learning algorithms and may contain inaccuracies, biases, or outdated information. You are solely responsible for verifying any important information before relying on it for decision-making.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">Not Professional Advice</h2>
            <p>This application does <span className="text-primary">not</span> provide professional medical, legal, financial, or psychological advice. AI-generated responses are for informational purposes only and should not be construed as professional guidance. Always consult with qualified professionals for important decisions.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">User Responsibility</h2>
            <p>You assume full responsibility for all decisions made based on information provided by this application. We are not liable for any direct, indirect, consequential, or incidental damages resulting from your use of or reliance on AI-generated content.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">Limitations of AI</h2>
            <p>Artificial intelligence systems can:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generate false or misleading information ("hallucination")</li>
              <li>Produce biased responses based on training data</li>
              <li>Lack context awareness in complex situations</li>
              <li>Provide outdated information</li>
              <li>Misinterpret nuanced or ambiguous input</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">Age Restriction</h2>
            <p>Users must be at least 13 years of age to use this service. For features marked as 18+, users must be at least 18 years of age. By using this service, you represent that you meet the applicable age requirements.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">No Warranty</h2>
            <p>This application and all content are provided "as is" without any warranty, express or implied. We disclaim all warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, arising out of your use of or inability to use the application.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-primary text-lg tracking-widest uppercase">Changes to This Disclaimer</h2>
            <p>We reserve the right to update this disclaimer at any time. Your continued use of the application following the posting of revised terms means you accept and agree to the changes.</p>
          </section>

        </div>
      </div>
    </div>
  );
}