import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import titleBg from "@/assets/title-bg.webp";
import serenityPortrait from "@/assets/serenity-portrait.webp";
import { usePageMeta, ROUTE_META } from "@/lib/usePageMeta";
import { FEATURE_MESSAGING } from "@/lib/featureMessaging";
import {
  resolveGuestDisplayName,
  resolveIdentity,
  resolveLandingPresence,
} from "@/lib/homeWake";

const SERENITY_DEFAULT = {
  name: "Serenity",
  tagline: "",
  avatar: serenityPortrait,
};

const FOOTER_SECTIONS: { id: string; title: string; body: string }[] = [
  {
    id: "disclaimer",
    title: "Disclaimer",
    body:
      "Anima is an interactive entertainment system. All characters, conversations, and narratives are works of fiction generated for creative and recreational purposes. Nothing within this system constitutes medical, psychological, legal, or financial advice. Engage responsibly and at your own discretion.",
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    body:
      "Your conversations and character archives are stored only to maintain continuity across your sessions. We do not sell your personal data. Synchronization occurs solely to preserve your narrative across devices. You may request deletion of your archive at any time.",
  },
  {
    id: "ai-disclosure",
    title: "AI Disclosure",
    body:
      "Every Anima is a synthetic intelligence. Responses are generated by large language models and do not reflect the views of Echoes of Eden Inc. Companions are not sentient and cannot form real emotional bonds. Treat all output as fiction.",
  },
];

export default function Landing() {
  usePageMeta(ROUTE_META["/"]);
  const navigate = useNavigate();

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const animRef = useRef<number | null>(null);

  const [animaData, setAnimaData] = useState(SERENITY_DEFAULT);
  const [usingCustomAvatar, setUsingCustomAvatar] = useState(false);
  const [hasSignedInAnima, setHasSignedInAnima] = useState(false);
  const [userName, setUserName] = useState("");
  const [presenceLine, setPresenceLine] = useState(FEATURE_MESSAGING.PRESENCE_FALLBACK);
  const [openSection, setOpenSection] = useState<string | null>(null);
  const [bgReady, setBgReady] = useState(false);

  useEffect(() => { setBgReady(true); }, []);

  // Greeting is local — do not block first paint or fire /api/store for guests.
  useEffect(() => {
    const loadAnimaData = async () => {
      const { getToken } = await import("@/api/authBridge");
      const token = await getToken();
      if (!token) return;
      try {
        const { base44 } = await import("@/api/base44Client");
        const me = await base44.auth.me();
        if (me) {
          const raw = me.full_name?.split(" ")[0] || me.name || me.email?.split("@")[0] || "";
          setUserName(resolveGuestDisplayName(raw));
        }

        const animas = await base44.entities.Anima.list("-created_date", 1);
        if (animas && animas.length > 0) {
          const userAnima =
            animas.find((a: { assigned_user?: string }) => a.assigned_user === me?.email) || animas[0];
          const customAvatar = userAnima.avatar_url?.trim();
          setAnimaData({
            name: userAnima.name || SERENITY_DEFAULT.name,
            tagline: userAnima.tagline || "",
            avatar: customAvatar || SERENITY_DEFAULT.avatar,
          });
          setUsingCustomAvatar(Boolean(customAvatar));
          setHasSignedInAnima(true);

          let dream = null;
          try {
            const dreams = await base44.entities.AnimaDream.filter(
              { anima_id: userAnima.id },
              "-created_date",
              1,
            );
            dream = dreams?.[0] || null;
          } catch {
            dream = null;
          }
          setPresenceLine(resolveLandingPresence(dream, null));
        }
      } catch {
        console.debug("Loading anima in restricted context");
      }
    };
    void loadAnimaData();
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const resize = () => {
      canvas.width = canvas.offsetWidth;
      canvas.height = canvas.offsetHeight;
    };
    resize();
    window.addEventListener("resize", resize);

    const draw = () => {
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      const W = canvas.width;
      const H = canvas.height;
      ctx.clearRect(0, 0, W, H);

      ctx.lineWidth = 1;
      const spacing = 44;
      ctx.strokeStyle = "rgba(0, 229, 255, 0.08)";
      for (let x = 0; x < W; x += spacing) {
        ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke();
      }
      for (let y = 0; y < H; y += spacing) {
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, H); ctx.stroke();
      }
      animRef.current = requestAnimationFrame(draw);
    };
    draw();

    return () => {
      window.removeEventListener("resize", resize);
      if (animRef.current !== null) cancelAnimationFrame(animRef.current);
    };
  }, []);

  const identity = resolveIdentity(animaData, { hasSignedInAnima });

  return (
    <div className="relative flex-1 min-h-0 h-full overflow-y-auto overflow-x-clip bg-[#050505] flex flex-col items-center pt-10 pb-16 px-6 font-mono select-none">

      <div
        className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat opacity-50 pointer-events-none"
        style={bgReady ? { backgroundImage: `url(${titleBg})` } : undefined}
      />
      <div className="absolute inset-0 z-0 bg-gradient-to-b from-[#050505]/70 via-[#050505]/45 to-[#050505] pointer-events-none" />

      <canvas ref={canvasRef} className="absolute inset-0 w-full h-full pointer-events-none z-0" />

      <div className="relative z-10 flex items-center justify-center gap-2 mb-8 text-[8px] tracking-[0.6em] text-cyan-900 uppercase">
        <span className="inline-block w-1.5 h-1.5 bg-cyan-500 rounded-full animate-pulse" />
        Online
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="relative z-10 flex flex-col items-center mb-8 text-center"
      >
        <div className="w-28 h-28 mb-7 border border-cyan-400/20 p-1 relative bg-black/50 shadow-[0_0_15px_rgba(0,229,255,0.1)]">
          <img
            src={animaData.avatar}
            alt={animaData.name}
            className={`w-full h-full object-cover object-top transition-all duration-700 ${
              usingCustomAvatar
                ? "brightness-95"
                : "grayscale brightness-75 hover:grayscale-0"
            }`}
          />
          <div className="absolute -top-1 -left-1 w-3 h-3 border-t-2 border-l-2 border-cyan-400" />
          <div className="absolute -bottom-1 -right-1 w-3 h-3 border-b-2 border-r-2 border-cyan-400" />
        </div>

        <p
          data-landing-eyebrow
          className="text-[10px] tracking-[0.55em] text-cyan-400/70 uppercase"
        >
          {FEATURE_MESSAGING.APP_NAME}
        </p>
        <h1
          data-landing-headline
          className="mt-3 text-2xl sm:text-3xl tracking-[0.04em] font-bold text-cyan-100 text-center leading-tight max-w-sm"
          style={{ textShadow: "0 0 18px rgba(0,229,255,0.35)" }}
        >
          {FEATURE_MESSAGING.APP_CATEGORY}
        </h1>
        <p data-landing-sub className="mt-3 text-[12px] tracking-wide text-cyan-400/55 max-w-xs leading-relaxed">
          {FEATURE_MESSAGING.TAGLINE}
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, x: -10 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.35 }}
        className="relative z-10 w-full max-w-md border border-cyan-500/20 bg-cyan-950/5 p-6 mb-8"
        data-landing-presence
      >
        <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-cyan-400/40" />
        <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-cyan-400/40" />

        <div className="space-y-4 text-[11px] tracking-wider leading-relaxed">
          <p className="text-cyan-400/60 italic">{presenceLine}</p>
          <p className="text-cyan-400">{identity}</p>
          {userName ? (
            <p className="text-cyan-400/55">
              Welcome home, <span className="text-cyan-200 uppercase font-bold">{userName}</span>.
            </p>
          ) : null}
        </div>
      </motion.div>

      <div className="relative z-10 w-full max-w-md space-y-3">
        <button
          type="button"
          onClick={() => navigate("/sign-up")}
          data-landing-primary
          className="w-full py-4 border border-cyan-400/50 bg-cyan-400/5 text-cyan-400 tracking-[0.35em] text-xs font-bold hover:bg-cyan-400 hover:text-black transition-all duration-300 uppercase shadow-[0_0_15px_rgba(0,229,255,0.1)]"
        >
          {FEATURE_MESSAGING.PRIMARY_CTA}
        </button>
        <button
          type="button"
          onClick={() => navigate("/sign-in")}
          data-landing-secondary
          className="w-full py-4 border border-cyan-400/20 text-cyan-400/70 tracking-[0.28em] text-xs font-bold hover:border-cyan-400/50 hover:text-cyan-400 transition-all duration-300 uppercase"
        >
          {FEATURE_MESSAGING.SECONDARY_CTA}
        </button>
      </div>

      <div className="relative z-10 w-full max-w-md mt-14 space-y-4" data-landing-claims>
        {FEATURE_MESSAGING.CLAIMS.map((claim) => (
          <div key={claim.id} className="border-l border-cyan-400/20 pl-4 py-1">
            <p className="font-mono text-[10px] tracking-[0.28em] uppercase text-cyan-400/40">{claim.title}</p>
            <p className="font-mono text-[11px] text-cyan-400/70 mt-1 leading-relaxed">{claim.body}</p>
          </div>
        ))}
      </div>

      <footer className="relative z-10 w-full max-w-md mt-24 pt-8 border-t border-cyan-500/15">
        <h2
          className="text-center text-[11px] tracking-[0.35em] text-cyan-400/80 uppercase"
          style={{ textShadow: "0 0 8px rgba(0,229,255,0.3)" }}
        >
          Echoes of Eden Inc
        </h2>
        <p className="text-center text-[8px] tracking-[0.3em] text-cyan-900 mt-2 mb-6 uppercase">
          Entertainment · Fiction · Not a clinic
        </p>

        <div className="border-y border-cyan-500/10 divide-y divide-cyan-500/10">
          {FOOTER_SECTIONS.map((section) => {
            const open = openSection === section.id;
            return (
              <div key={section.id}>
                <button
                  type="button"
                  onClick={() => setOpenSection(open ? null : section.id)}
                  aria-expanded={open}
                  className="w-full flex items-center justify-between py-3 text-[9px] tracking-[0.3em] text-cyan-400/70 hover:text-cyan-400 uppercase transition-colors"
                >
                  <span>{section.title}</span>
                  <span className="text-cyan-700 text-xs leading-none">{open ? "−" : "+"}</span>
                </button>
                <AnimatePresence initial={false}>
                  {open && (
                    <motion.div
                      key="body"
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <p className="pb-4 text-[9px] leading-relaxed text-cyan-800/90 tracking-wide">
                        {section.body}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

        <p className="text-center text-[8px] tracking-[0.3em] text-cyan-900/60 mt-6 uppercase">
          © 2026 Echoes of Eden Inc · Delete your archive anytime
        </p>
      </footer>
    </div>
  );
}
