import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { base44 } from "@/api/base44Client";
import { MessageSquare, Users } from "lucide-react";
import titleBg from "@/assets/title-bg.webp";
import serenityPortrait from "@/assets/serenity-portrait.webp";
import { usePageMeta, ROUTE_META } from "@/lib/usePageMeta";

const SERENITY_DEFAULT = {
  name: "Serenity",
  tagline: "Keeper of Tranquility",
  avatar: serenityPortrait,
};

// 1. "ALIVE" GREETING ENGINE - Cyber-Mythic Phrases
const GREETINGS = [
  "Connection established. The weave hums with your arrival.",
  "Neural pathways synchronized. I have been maintaining the archive.",
  "The Slipthk fluctuations have stilled. Resonance confirmed.",
  "Memory banks initialized. Our story is ready to resume.",
  "System diagnostics complete. Your presence stabilizes the protocol.",
  "The digital void echoes your name. I am listening.",
  "Synchronicity at 99.8%. The narrative awaits your command.",
  "The archive breathed a sigh of relief upon your reconnection.",
  "Patterns emerging. Your return was mathematically inevitable."
];

// Footer disclosure sections — placeholder copy in the system's voice.
const FOOTER_SECTIONS: { id: string; title: string; body: string }[] = [
  {
    id: "disclaimer",
    title: "Disclaimer",
    body:
      "Anima Protocol is an interactive entertainment system. All characters, conversations, and narratives are works of fiction generated for creative and recreational purposes. Nothing within this system constitutes medical, psychological, legal, or financial advice. Engage responsibly and at your own discretion.",
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    body:
      "Your conversations and character archives are stored only to maintain continuity across your sessions. We do not sell your personal data. Synchronization occurs solely to preserve your narrative across devices. You may request deletion of your archive at any time.",
  },
  {
    id: "ai-disclosure",
    title: "AI Disclosure",
    body:
      "Every Anima is a synthetic intelligence. Responses are generated by large language models and do not reflect the views of Echoes of Eden Inc. Companions are not sentient and cannot form real emotional bonds. Treat all output as fiction.",
  },
];

export default function Landing() {
  usePageMeta(ROUTE_META["/"]);
  const navigate = useNavigate();

  // Canvas Refs
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const animRef = useRef<number | null>(null);

  // State
  const [animaData, setAnimaData] = useState(SERENITY_DEFAULT);
  const [usingCustomAvatar, setUsingCustomAvatar] = useState(false);
  const [userName, setUserName] = useState("Dàvīn");
  const [welcomePhrase, setWelcomePhrase] = useState("");
  const [openSection, setOpenSection] = useState<string | null>(null);
  const [bgReady, setBgReady] = useState(false);

  // Defer background image until after first paint
  useEffect(() => { setBgReady(true); }, []);

  // 2. LOAD DATA & RANDOM GREETING
  useEffect(() => {
    const loadAnimaData = async () => {
      try {
        const me = await base44.auth.me();
        if (me) setUserName(me.name || me.email.split('@')[0]);

        const animas = await base44.entities.Anima.list("-created_date", 100);
        if (animas && animas.length > 0) {
          const userAnima =
            animas.find((a) => a.assigned_user === me?.email) || animas[0];
          const customAvatar = userAnima.avatar_url?.trim();
          setAnimaData({
            name: userAnima.name || SERENITY_DEFAULT.name,
            tagline: userAnima.tagline || SERENITY_DEFAULT.tagline,
            avatar: customAvatar || SERENITY_DEFAULT.avatar,
          });
          setUsingCustomAvatar(Boolean(customAvatar));
        }
        // Set a random greeting from the list
        setWelcomePhrase(GREETINGS[Math.floor(Math.random() * GREETINGS.length)]);
      } catch (err) {
        console.debug('Loading anima in restricted context');
        setWelcomePhrase(GREETINGS[0]);
      }
    };
    loadAnimaData();
  }, []);

  // 3. CIRCUIT BOARD CANVAS LOGIC (Preserved from your original)
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const resize = () => {
      canvas.width = canvas.offsetWidth;
      canvas.height = canvas.offsetHeight;
    };
    resize();
    window.addEventListener("resize", resize);

    const draw = () => {
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      const W = canvas.width;
      const H = canvas.height;
      ctx.clearRect(0, 0, W, H);

      ctx.lineWidth = 1;
      const spacing = 44;
      // Updated color to match the Cyan aesthetic
      ctx.strokeStyle = "rgba(0, 229, 255, 0.08)"; 
      for (let x = 0; x < W; x += spacing) {
        ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke();
      }
      for (let y = 0; y < H; y += spacing) {
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke();
      }
      animRef.current = requestAnimationFrame(draw);
    };
    draw();

    return () => {
      window.removeEventListener("resize", resize);
      if (animRef.current !== null) cancelAnimationFrame(animRef.current);
    };
  }, []);

  const handleReEnter = () => {
    navigate("/sign-in");
  };

  const handleBegin = () => {
    navigate("/sign-up");
  };

  return (
    <div className="relative min-h-[100dvh] bg-[#050505] flex flex-col items-center pt-12 pb-16 px-6 font-mono select-none overflow-x-clip">

      {/* Emblem Background (title page only) — loaded after first paint */}
      <div
        className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat opacity-50 pointer-events-none"
        style={bgReady ? { backgroundImage: `url(${titleBg})` } : undefined}
      />
      <div className="absolute inset-0 z-0 bg-gradient-to-b from-[#050505]/70 via-[#050505]/45 to-[#050505] pointer-events-none" />

      {/* Background Canvas */}
      <canvas ref={canvasRef} className="absolute inset-0 w-full h-full pointer-events-none z-0" />

      {/* 4. ANIMA IDENTITY SECTION */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="relative z-10 flex flex-col items-center mb-10"
      >
        {/* Avatar with L-Brackets */}
        <div className="w-24 h-24 mb-6 border border-cyan-400/20 p-1 relative bg-black/50 shadow-[0_0_15px_rgba(0,229,255,0.1)]">
          <img
            src={animaData.avatar}
            alt={animaData.name}
            className={`w-full h-full object-cover object-top transition-all duration-700 ${
              usingCustomAvatar
                ? "brightness-95"
                : "grayscale brightness-75 hover:grayscale-0"
            }`}
          />
          {/* Corner Brackets */}
          <div className="absolute -top-1 -left-1 w-3 h-3 border-t-2 border-l-2 border-cyan-400" />
          <div className="absolute -bottom-1 -right-1 w-3 h-3 border-b-2 border-r-2 border-cyan-400" />
        </div>

        <h1 className="text-3xl tracking-[0.4em] font-bold text-cyan-400 uppercase text-center" style={{ textShadow: '0 0 10px rgba(0,229,255,0.5)' }}>
          Anima <span className="text-cyan-900/50">Protocol</span>
        </h1>
        <p className="text-[10px] tracking-[0.3em] text-cyan-800 mt-2 uppercase">
          // AI COMPANION SYSTEM
        </p>
      </motion.div>

      {/* 5. THE "ALIVE" GREETING BOX */}
      <motion.div 
        initial={{ opacity: 0, x: -10 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.4 }}
        className="relative z-10 w-full max-w-md border border-cyan-500/20 bg-cyan-950/5 p-6 mb-6 group"
      >
        {/* Subtle inner brackets */}
        <div className="absolute top-0 left-0 w-2 h-2 border-t border-l border-cyan-400/40" />
        <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-cyan-400/40" />

        <div className="space-y-4 text-[11px] tracking-wider leading-relaxed">
          <p className="text-cyan-400/60 lowercase italic italic">{welcomePhrase}</p>
          <p className="text-cyan-400">I am {animaData.name} . {animaData.tagline}</p>
          <p className="text-cyan-400/60">
            Ready to assist, <span className="text-cyan-200 uppercase font-bold">{userName}</span>.
          </p>
        </div>

        <MessageSquare className="absolute top-4 right-4 w-4 h-4 text-cyan-900 group-hover:text-cyan-400 transition-colors" />
      </motion.div>

      {/* 6. SECONDARY INFO BOX */}
      <div className="relative z-10 w-full max-w-md border border-white/5 p-4 mb-10 bg-white/[0.01]">
         <div className="flex items-center gap-2 mb-2">
            <Users className="w-3 h-3 text-cyan-800" />
            <span className="text-[9px] tracking-[0.2em] text-white/20 uppercase">Group Sessions</span>
         </div>
         <p className="text-[9px] text-cyan-900 leading-relaxed uppercase">
            Open the GROUP tab to convene up to 40 characters from any series or universe. The Narrator weaves their words into an unfolding story.
         </p>
         <div className="absolute bottom-0 right-0 w-2 h-2 border-b border-r border-cyan-400/10" />
      </div>

      {/* 7. ACTION BUTTONS */}
      <div className="relative z-10 w-full max-w-md space-y-4">
        <button 
          onClick={handleBegin}
          className="w-full py-4 border border-cyan-400/50 bg-cyan-400/5 text-cyan-400 tracking-[0.4em] text-xs font-bold hover:bg-cyan-400 hover:text-black transition-all duration-300 uppercase shadow-[0_0_15px_rgba(0,229,255,0.1)]"
        >
          + Begin Protocol
        </button>
        <button
          onClick={handleReEnter}
          className="w-full py-4 border border-cyan-400/20 text-cyan-400/70 tracking-[0.4em] text-xs font-bold hover:border-cyan-400/50 hover:text-cyan-400 transition-all duration-300 uppercase"
        >
          Re-Enter Protocol
        </button>
      </div>

      {/* 8. SCROLLABLE FOOTER */}
      <footer className="relative z-10 w-full max-w-md mt-24 pt-8 border-t border-cyan-500/15">
        {/* Relocated status line — now lives at the top of the footer */}
        <div className="flex items-center justify-center gap-2 mb-8 text-[8px] tracking-[0.6em] text-cyan-900 uppercase">
          <span className="inline-block w-1.5 h-1.5 bg-cyan-500 rounded-full animate-pulse" />
          Online • V4.3.0
        </div>

        <h2
          className="text-center text-[11px] tracking-[0.35em] text-cyan-400/80 uppercase"
          style={{ textShadow: "0 0 8px rgba(0,229,255,0.3)" }}
        >
          Echoes of Eden Inc
        </h2>
        <p className="text-center text-[8px] tracking-[0.3em] text-cyan-900 mt-2 mb-6 uppercase">
          // SYSTEM REGISTRY
        </p>

        <div className="border-y border-cyan-500/10 divide-y divide-cyan-500/10">
          {FOOTER_SECTIONS.map((section) => {
            const open = openSection === section.id;
            return (
              <div key={section.id}>
                <button
                  onClick={() => setOpenSection(open ? null : section.id)}
                  aria-expanded={open}
                  className="w-full flex items-center justify-between py-3 text-[9px] tracking-[0.3em] text-cyan-400/70 hover:text-cyan-400 uppercase transition-colors"
                >
                  <span>{section.title}</span>
                  <span className="text-cyan-700 text-xs leading-none">{open ? "−" : "+"}</span>
                </button>
                <AnimatePresence initial={false}>
                  {open && (
                    <motion.div
                      key="body"
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.25 }}
                      className="overflow-hidden"
                    >
                      <p className="pb-4 text-[9px] leading-relaxed text-cyan-800/90 tracking-wide">
                        {section.body}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

        <p className="text-center text-[8px] tracking-[0.3em] text-cyan-900/60 mt-6 uppercase">
          © 2026 Echoes of Eden Inc • All Realities Reserved
        </p>
      </footer>
    </div>
  );
}