// @ts-check
/**
 * Original Energy Fragment library — Anima Protocol battle data.
 *
 * Inspired by Battle Network chip families (see battleChipAccount.js) but
 * named, numbered, and described as new programs. Weapons summoned from a
 * fragment are ethereal (ghost-steel, light-edge, no solid mass).
 */

/** @typedef {"standard" | "apex" | "nova"} FragmentClass */
/** @typedef {"void" | "ember" | "tide" | "volt" | "grove"} FragmentElement */
/**
 * @typedef {"none" | "blade" | "gale" | "mark" | "shatter" | "summon" | "mend"} FragmentTactic
 */
/**
 * @typedef {"cannon" | "spreader" | "bomb" | "sword" | "wave" | "tower" | "quake" | "fist" | "dash" | "howitzer" | "arrow" | "homing" | "sheet" | "gaia" | "orb" | "orbit" | "gyre" | "coil" | "drain" | "aura" | "panel" | "hammer" | "shield" | "mend" | "steal" | "field" | "escape" | "silence" | "repair" | "chrono" | "rain" | "mine" | "seek" | "remote" | "lockon" | "wick" | "idol" | "cube" | "buster" | "gauge" | "fade" | "wrap" | "sigil" | "prism" | "gravity" | "rift"} SummonKind
 */

/**
 * @typedef {object} EnergyFragment
 * @property {string} id
 * @property {string} name
 * @property {number} libraryNo
 * @property {string} family
 * @property {FragmentClass} class
 * @property {FragmentElement} element
 * @property {FragmentTactic} tactic
 * @property {number | null} power
 * @property {number} mb
 * @property {string[]} codes
 * @property {string} description
 * @property {SummonKind} summon
 * @property {string} inspiredByFamily
 * @property {string} [summonNote]
 */

/**
 * @param {Omit<EnergyFragment, "libraryNo">[]} rows
 * @returns {EnergyFragment[]}
 */
function numberLibrary(rows) {
  return rows.map((row, i) => ({ ...row, libraryNo: i + 1 }));
}

/** @type {EnergyFragment[]} */
export const ENERGY_FRAGMENTS = numberLibrary([
  // —— Pulse (Cannon) ——
  {
    id: "pulse-emitter",
    name: "Pulse Emitter",
    family: "pulse",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 40,
    mb: 6,
    codes: ["A", "B", "C", "*"],
    description: "A ghost cannon coalesces on the forearm and looses one clean pulse.",
    summon: "cannon",
    inspiredByFamily: "cannon",
    summonNote: "Translucent barrel, cyan muzzle-light, no recoil mass.",
  },
  {
    id: "high-pulse",
    name: "High Pulse",
    family: "pulse",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 100,
    mb: 24,
    codes: ["L", "M", "N", "*"],
    description: "Heavier ether-cannon. The barrel lengthens into a ribbon of light.",
    summon: "cannon",
    inspiredByFamily: "cannon",
  },
  {
    id: "apex-pulse",
    name: "Apex Pulse",
    family: "pulse",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 180,
    mb: 38,
    codes: ["R", "S", "T", "*"],
    description: "A cathedral of glass-steel around the arm. One devastating pulse.",
    summon: "cannon",
    inspiredByFamily: "cannon",
  },

  // —— Halo (Spreader) ——
  {
    id: "halo-burst",
    name: "Halo Burst",
    family: "halo",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 30,
    mb: 8,
    codes: ["A", "B", "C", "*"],
    description: "Shot continues through the target as a ring of pale light.",
    summon: "spreader",
    inspiredByFamily: "spreader",
  },
  {
    id: "cross-halo",
    name: "Cross Halo",
    family: "halo",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 30,
    mb: 10,
    codes: ["H", "L", "P"],
    description: "Diagonal blast cross. Four ghost petals bloom from the hit panel.",
    summon: "spreader",
    inspiredByFamily: "spreader",
  },
  {
    id: "tide-halo",
    name: "Tide Halo",
    family: "halo",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 50,
    mb: 12,
    codes: ["A", "Q", "W"],
    description: "Aqua-glass spreader. Bubbles hang in the air after the shot.",
    summon: "spreader",
    inspiredByFamily: "spreader",
  },
  {
    id: "cinder-halo",
    name: "Cinder Halo",
    family: "halo",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 70,
    mb: 14,
    codes: ["F", "H", "N"],
    description: "Ember ring that keeps burning one panel past the hit.",
    summon: "spreader",
    inspiredByFamily: "spreader",
  },

  // —— Seed (Bomb) ——
  {
    id: "ember-seed",
    name: "Ember Seed",
    family: "seed",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 50,
    mb: 6,
    codes: ["B", "L", "T", "*"],
    description: "Throw a condensed spark three panels deep. It detonates as smoke-light.",
    summon: "bomb",
    inspiredByFamily: "bomb",
  },
  {
    id: "twin-seed",
    name: "Twin Seed",
    family: "seed",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 16,
    codes: ["O", "T", "T"],
    description: "Paired seeds that bloom in a plus-shape of ghost fire.",
    summon: "bomb",
    inspiredByFamily: "bomb",
  },
  {
    id: "cross-seed",
    name: "Cross Seed",
    family: "seed",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 18,
    codes: ["C", "D", "K"],
    description: "Cross-shaped ether bloom, depth 3.",
    summon: "bomb",
    inspiredByFamily: "bomb",
  },
  {
    id: "nova-seed",
    name: "Nova Seed",
    family: "seed",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 90,
    mb: 22,
    codes: ["B", "G", "O"],
    description: "A large, slow seed. The explosion looks like a collapsing star.",
    summon: "bomb",
    inspiredByFamily: "bomb",
  },

  // —— Phantom (Sword) ——
  {
    id: "phantom-edge",
    name: "Phantom Edge",
    family: "phantom",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: 80,
    mb: 8,
    codes: ["H", "L", "S", "*"],
    description: "A one-panel saber of glass light. No weight, only edge.",
    summon: "sword",
    inspiredByFamily: "sword",
    summonNote: "Translucent katana, afterimage trail, no scabbard.",
  },
  {
    id: "wide-phantom",
    name: "Wide Phantom",
    family: "phantom",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: 80,
    mb: 10,
    codes: ["L", "S", "V"],
    description: "Column cut. The blade fans into a sheet of moonlight.",
    summon: "sword",
    inspiredByFamily: "sword",
  },
  {
    id: "long-phantom",
    name: "Long Phantom",
    family: "phantom",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: 100,
    mb: 12,
    codes: ["E", "N", "S"],
    description: "Two-panel reach. The tip dissolves into mist past the second tile.",
    summon: "sword",
    inspiredByFamily: "sword",
  },
  {
    id: "knight-veil",
    name: "Knight Veil",
    family: "phantom",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: 150,
    mb: 22,
    codes: ["K", "N", "W"],
    description: "Three-panel legendary cut. Armor of the wielder turns to stained glass.",
    summon: "sword",
    inspiredByFamily: "sword",
  },
  {
    id: "cinder-veil",
    name: "Cinder Veil",
    family: "phantom",
    class: "standard",
    element: "ember",
    tactic: "blade",
    power: 120,
    mb: 16,
    codes: ["F", "N", "P"],
    description: "Column slash wrapped in slow fire that never quite burns the hand.",
    summon: "sword",
    inspiredByFamily: "sword",
  },
  {
    id: "tide-veil",
    name: "Tide Veil",
    family: "phantom",
    class: "standard",
    element: "tide",
    tactic: "blade",
    power: 150,
    mb: 18,
    codes: ["A", "M", "P"],
    description: "Column slash of liquid glass.",
    summon: "sword",
    inspiredByFamily: "sword",
  },
  {
    id: "spark-veil",
    name: "Spark Veil",
    family: "phantom",
    class: "standard",
    element: "volt",
    tactic: "blade",
    power: 130,
    mb: 17,
    codes: ["E", "K", "N"],
    description: "Column slash threaded with pale lightning.",
    summon: "sword",
    inspiredByFamily: "sword",
  },

  // —— Echo Debt (Muramasa) ——
  {
    id: "echo-debt",
    name: "Echo Debt",
    family: "echo-debt",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: null,
    mb: 28,
    codes: ["M"],
    description: "A hungry blade. Power equals HP already spent this fight.",
    summon: "sword",
    inspiredByFamily: "muramasa",
    summonNote: "Black-glass edge with a red afterimage that pulses with missing HP.",
  },

  // —— Tremor (Shockwave) ——
  {
    id: "tremor-veil",
    name: "Tremor Veil",
    family: "tremor",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 60,
    mb: 10,
    codes: ["C", "K", "L"],
    description: "Piercing ground-light that runs the row.",
    summon: "wave",
    inspiredByFamily: "shockwave",
  },
  {
    id: "sonic-veil",
    name: "Sonic Veil",
    family: "tremor",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 16,
    codes: ["D", "N", "S"],
    description: "Faster piercing wave. Air rings like struck crystal.",
    summon: "wave",
    inspiredByFamily: "shockwave",
  },
  {
    id: "dynamo-veil",
    name: "Dynamo Veil",
    family: "tremor",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 100,
    mb: 22,
    codes: ["C", "R", "V"],
    description: "Heavy piercing wave that shears obstacles.",
    summon: "wave",
    inspiredByFamily: "shockwave",
  },

  // —— Spire (Tower) ——
  {
    id: "flame-spire",
    name: "Flame Spire",
    family: "spire",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 100,
    mb: 18,
    codes: ["F", "R", "T"],
    description: "A column of ghost-fire that can be walked up or down.",
    summon: "tower",
    inspiredByFamily: "tower",
  },
  {
    id: "tide-spire",
    name: "Tide Spire",
    family: "spire",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 120,
    mb: 20,
    codes: ["A", "C", "M"],
    description: "Water-glass pillar, steerable on the column.",
    summon: "tower",
    inspiredByFamily: "tower",
  },
  {
    id: "grove-spire",
    name: "Grove Spire",
    family: "spire",
    class: "standard",
    element: "grove",
    tactic: "none",
    power: 140,
    mb: 22,
    codes: ["G", "S", "W"],
    description: "A log of living light that rises and falls.",
    summon: "tower",
    inspiredByFamily: "tower",
  },

  // —— Fault (Quake) ——
  {
    id: "fault-line",
    name: "Fault Line",
    family: "fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 90,
    mb: 14,
    codes: ["A", "K", "Q"],
    description: "Thrown stone-ghost that cracks the landing panel, depth 3.",
    summon: "quake",
    inspiredByFamily: "quake",
  },
  {
    id: "fault-line-2",
    name: "Fault Line 2",
    family: "fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 120,
    mb: 20,
    codes: ["B", "Q", "V"],
    description: "Heavier fault. Panels spiderweb with light before they break.",
    summon: "quake",
    inspiredByFamily: "quake",
  },
  {
    id: "fault-line-3",
    name: "Fault Line 3",
    family: "fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 150,
    mb: 26,
    codes: ["C", "D", "Q"],
    description: "The landing tile remembers being stone, then forgets.",
    summon: "quake",
    inspiredByFamily: "quake",
  },

  // —— Geist (Punch) ——
  {
    id: "geist-fist",
    name: "Geist Fist",
    family: "geist",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 160,
    mb: 12,
    codes: ["B", "G", "T"],
    description: "A huge translucent fist. Knocks obstacles into mist.",
    summon: "fist",
    inspiredByFamily: "punch",
  },
  {
    id: "frost-geist",
    name: "Frost Geist",
    family: "geist",
    class: "standard",
    element: "tide",
    tactic: "shatter",
    power: 150,
    mb: 14,
    codes: ["A", "I", "P"],
    description: "Ice-glass punch. Range 1, guard-pierce.",
    summon: "fist",
    inspiredByFamily: "punch",
  },

  // —— Afterimage / Breaker ——
  {
    id: "afterimage-rush",
    name: "Afterimage Rush",
    family: "afterimage",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 50,
    mb: 8,
    codes: ["D", "R", "S"],
    description: "Dash the row as stacked ghost-bodies. Everything in the path is knocked.",
    summon: "dash",
    inspiredByFamily: "dash",
  },
  {
    id: "panel-breaker",
    name: "Panel Breaker",
    family: "breaker",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 200,
    mb: 28,
    codes: ["H", "O", "W"],
    description: "Howitzer of condensed gravity. Depth 3, breaks the tile.",
    summon: "howitzer",
    inspiredByFamily: "howitzer",
  },

  // —— Gleam (Arrow) ——
  {
    id: "tri-gleam",
    name: "Tri Gleam",
    family: "gleam",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 40,
    mb: 10,
    codes: ["A", "B", "C"],
    description: "Three needles of light, fired as a burst.",
    summon: "arrow",
    inspiredByFamily: "arrow",
  },
  {
    id: "tri-spearlight",
    name: "Tri Spearlight",
    family: "gleam",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 50,
    mb: 14,
    codes: ["J", "K", "L"],
    description: "Three longer spears. They fade instead of sticking.",
    summon: "arrow",
    inspiredByFamily: "arrow",
  },
  {
    id: "tri-lanceveil",
    name: "Tri Lanceveil",
    family: "gleam",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 60,
    mb: 18,
    codes: ["P", "Q", "R"],
    description: "Three lances of veil-steel.",
    summon: "arrow",
    inspiredByFamily: "arrow",
  },

  // —— Wisp (Ratton) ——
  {
    id: "homing-wisp",
    name: "Homing Wisp",
    family: "wisp",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 90,
    mb: 14,
    codes: ["H", "R", "T"],
    description: "A will-o-wisp missile that may turn once.",
    summon: "homing",
    inspiredByFamily: "ratton",
  },
  {
    id: "homing-wisp-2",
    name: "Homing Wisp 2",
    family: "wisp",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 110,
    mb: 20,
    codes: ["J", "K", "W"],
    description: "Brighter wisp, one turn, harder to shake.",
    summon: "homing",
    inspiredByFamily: "ratton",
  },
  {
    id: "homing-wisp-3",
    name: "Homing Wisp 3",
    family: "wisp",
    class: "standard",
    element: "ember",
    tactic: "mark",
    power: 130,
    mb: 26,
    codes: ["N", "O", "P"],
    description: "Scorching wisp. Leaves a trail of cinder motes.",
    summon: "homing",
    inspiredByFamily: "ratton",
  },

  // —— Sheet (Row wave) ——
  {
    id: "tide-sheet",
    name: "Tide Sheet",
    family: "sheet",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 80,
    mb: 16,
    codes: ["A", "C", "E"],
    description: "Three-row wave of glass water.",
    summon: "sheet",
    inspiredByFamily: "row-wave",
  },
  {
    id: "ember-sheet",
    name: "Ember Sheet",
    family: "sheet",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 100,
    mb: 20,
    codes: ["F", "H", "J"],
    description: "Three-row lava-light.",
    summon: "sheet",
    inspiredByFamily: "row-wave",
  },
  {
    id: "titan-sheet",
    name: "Titan Sheet",
    family: "sheet",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 160,
    mb: 32,
    codes: ["T", "U", "V"],
    description: "Giant three-row tide. The field looks briefly underwater.",
    summon: "sheet",
    inspiredByFamily: "row-wave",
  },

  // —— Rolling fault / Drift spark / Orbit ——
  {
    id: "rolling-fault",
    name: "Rolling Fault",
    family: "rolling-fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 100,
    mb: 18,
    codes: ["G", "S", "V"],
    description: "Explosion that walks three columns forward.",
    summon: "gaia",
    inspiredByFamily: "gaia",
  },
  {
    id: "rolling-fault-2",
    name: "Rolling Fault 2",
    family: "rolling-fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 130,
    mb: 24,
    codes: ["G", "T", "W"],
    description: "Heavier rolling blast.",
    summon: "gaia",
    inspiredByFamily: "gaia",
  },
  {
    id: "rolling-fault-3",
    name: "Rolling Fault 3",
    family: "rolling-fault",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 160,
    mb: 30,
    codes: ["G", "U", "X"],
    description: "The ground forgets it was ever solid.",
    summon: "gaia",
    inspiredByFamily: "gaia",
  },
  {
    id: "drift-spark",
    name: "Drift Spark",
    family: "drift-spark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 90,
    mb: 14,
    codes: ["E", "L", "T"],
    description: "A slow orb of lightning that rolls a row.",
    summon: "orb",
    inspiredByFamily: "thunder",
  },
  {
    id: "drift-spark-2",
    name: "Drift Spark 2",
    family: "drift-spark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 120,
    mb: 20,
    codes: ["E", "M", "U"],
    description: "Fatter spark, same lazy path.",
    summon: "orb",
    inspiredByFamily: "thunder",
  },
  {
    id: "drift-spark-3",
    name: "Drift Spark 3",
    family: "drift-spark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 150,
    mb: 26,
    codes: ["E", "N", "V"],
    description: "Storm-core orb.",
    summon: "orb",
    inspiredByFamily: "thunder",
  },
  {
    id: "orbit-arc",
    name: "Orbit Arc",
    family: "orbit-arc",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 100,
    mb: 16,
    codes: ["O", "R", "Z"],
    description: "Lightning circles you once, then fades.",
    summon: "orbit",
    inspiredByFamily: "ringzap",
  },
  {
    id: "orbit-arc-2",
    name: "Orbit Arc 2",
    family: "orbit-arc",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 100,
    mb: 20,
    codes: ["O", "S", "Y"],
    description: "Two orbits of pale voltage.",
    summon: "orbit",
    inspiredByFamily: "ringzap",
  },
  {
    id: "orbit-arc-3",
    name: "Orbit Arc 3",
    family: "orbit-arc",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 100,
    mb: 24,
    codes: ["O", "T", "X"],
    description: "Three rings. You look briefly like a haloed planet.",
    summon: "orbit",
    inspiredByFamily: "ringzap",
  },

  // —— Gyre / Coil / Siphon ——
  {
    id: "ether-gyre",
    name: "Ether Gyre",
    family: "gyre",
    class: "standard",
    element: "void",
    tactic: "gale",
    power: 30,
    mb: 10,
    codes: ["T", "Y", "Z"],
    description: "A twister of motes. Hits 3 times.",
    summon: "gyre",
    inspiredByFamily: "tornado",
  },
  {
    id: "storm-gyre",
    name: "Storm Gyre",
    family: "gyre",
    class: "standard",
    element: "void",
    tactic: "gale",
    power: 30,
    mb: 16,
    codes: ["H", "U", "V"],
    description: "Five-hit gyre.",
    summon: "gyre",
    inspiredByFamily: "tornado",
  },
  {
    id: "cyclone-gyre",
    name: "Cyclone Gyre",
    family: "gyre",
    class: "standard",
    element: "void",
    tactic: "gale",
    power: 30,
    mb: 22,
    codes: ["C", "D", "Y"],
    description: "Eight-hit gyre. The panel looks uninhabitable.",
    summon: "gyre",
    inspiredByFamily: "tornado",
  },
  {
    id: "coil-wisp",
    name: "Coil Wisp",
    family: "coil",
    class: "standard",
    element: "grove",
    tactic: "none",
    power: 130,
    mb: 20,
    codes: ["S", "N", "K"],
    description: "A squirming serpent of grove-light.",
    summon: "coil",
    inspiredByFamily: "snake",
  },
  {
    id: "coil-wisp-2",
    name: "Coil Wisp 2",
    family: "coil",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 140,
    mb: 24,
    codes: ["E", "S", "V"],
    description: "Shocking coil.",
    summon: "coil",
    inspiredByFamily: "snake",
  },
  {
    id: "coil-wisp-3",
    name: "Coil Wisp 3",
    family: "coil",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 150,
    mb: 28,
    codes: ["F", "S", "W"],
    description: "Scorching coil.",
    summon: "coil",
    inspiredByFamily: "snake",
  },
  {
    id: "siphon-veil",
    name: "Siphon Veil",
    family: "siphon",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 50,
    mb: 12,
    codes: ["A", "D", "S"],
    description: "Stand still. Threads of light drink HP from the nearest virus.",
    summon: "drain",
    inspiredByFamily: "drain",
  },
  {
    id: "siphon-veil-2",
    name: "Siphon Veil 2",
    family: "siphon",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 70,
    mb: 18,
    codes: ["B", "E", "T"],
    description: "Stronger drain threads.",
    summon: "drain",
    inspiredByFamily: "drain",
  },
  {
    id: "siphon-veil-3",
    name: "Siphon Veil 3",
    family: "siphon",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 90,
    mb: 24,
    codes: ["C", "F", "U"],
    description: "The virus's outline goes thin as paper.",
    summon: "drain",
    inspiredByFamily: "drain",
  },
  {
    id: "aura-ignition",
    name: "Aura Ignition",
    family: "ignition",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: 180,
    mb: 22,
    codes: ["B", "F", "N"],
    description: "All adjacent panels bloom with ghost-flame.",
    summon: "aura",
    inspiredByFamily: "bodyburn",
  },

  // —— Terrain / hammer / guard ——
  {
    id: "unmake-tile",
    name: "Unmake Tile",
    family: "unmake",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["B", "S", "X"],
    description: "Erase one panel into a hole of starfield, range 1.",
    summon: "panel",
    inspiredByFamily: "xpanel",
  },
  {
    id: "unmake-column",
    name: "Unmake Column",
    family: "unmake",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 14,
    codes: ["B", "D", "R"],
    description: "Erase a whole column.",
    summon: "panel",
    inspiredByFamily: "xpanel",
  },
  {
    id: "shatter-mallet",
    name: "Shatter Mallet",
    family: "mallet",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 220,
    mb: 18,
    codes: ["H", "M", "T"],
    description: "A hammer of cracked glass. Range 1, cubes go to dust.",
    summon: "hammer",
    inspiredByFamily: "hammer",
  },
  {
    id: "met-veil",
    name: "Met Veil",
    family: "metveil",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 6,
    codes: ["A", "C", "E", "*"],
    description: "Hold to raise a helmet of light. Parries for a few seconds.",
    summon: "shield",
    inspiredByFamily: "guard",
  },
  {
    id: "iron-veil",
    name: "Iron Veil",
    family: "metveil",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 10,
    codes: ["I", "R", "N"],
    description: "A taller shield of smoked glass.",
    summon: "shield",
    inspiredByFamily: "guard",
  },

  // —— Mend ——
  {
    id: "mend-10",
    name: "Mend 10",
    family: "mend",
    class: "standard",
    element: "void",
    tactic: "mend",
    power: 10,
    mb: 4,
    codes: ["A", "D", "L", "*"],
    description: "A brief halo. Restores 10 HP.",
    summon: "mend",
    inspiredByFamily: "recovery",
  },
  {
    id: "mend-50",
    name: "Mend 50",
    family: "mend",
    class: "standard",
    element: "void",
    tactic: "mend",
    power: 50,
    mb: 10,
    codes: ["C", "L", "P"],
    description: "Restores 50 HP as drifting motes return to the body.",
    summon: "mend",
    inspiredByFamily: "recovery",
  },
  {
    id: "mend-120",
    name: "Mend 120",
    family: "mend",
    class: "standard",
    element: "void",
    tactic: "mend",
    power: 120,
    mb: 32,
    codes: ["F", "P", "S"],
    description: "Restores 120 HP.",
    summon: "mend",
    inspiredByFamily: "recovery",
  },
  {
    id: "mend-300",
    name: "Mend 300",
    family: "mend",
    class: "standard",
    element: "void",
    tactic: "mend",
    power: 300,
    mb: 48,
    codes: ["J", "M", "T"],
    description: "A full reconstitution. Rare, heavy MB.",
    summon: "mend",
    inspiredByFamily: "recovery",
  },

  // —— Field control ——
  {
    id: "claim-column",
    name: "Claim Column",
    family: "claim",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 10,
    codes: ["S", "*"],
    description: "The nearest enemy column becomes yours — tiles turn pale gold.",
    summon: "steal",
    inspiredByFamily: "steal",
  },
  {
    id: "fracture-field",
    name: "Fracture Field",
    family: "fracture",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 14,
    codes: ["G", "S", "U"],
    description: "Every panel cracks. The next step may fall through.",
    summon: "field",
    inspiredByFamily: "geddon",
  },
  {
    id: "void-field",
    name: "Void Field",
    family: "fracture",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 20,
    codes: ["G", "V", "W"],
    description: "Empty panels unmake into holes.",
    summon: "field",
    inspiredByFamily: "geddon",
  },
  {
    id: "jack-out",
    name: "Jack Out",
    family: "jackout",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 4,
    codes: ["F", "H", "L", "*"],
    description: "Leave most virus battles. Bosses ignore it.",
    summon: "escape",
    inspiredByFamily: "escape",
  },
  {
    id: "data-silence",
    name: "Data Silence",
    family: "silence",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 12,
    codes: ["F", "I", "N"],
    description: "Scrub the enemy's queued fragment. Their next summon never arrives.",
    summon: "silence",
    inspiredByFamily: "interrupt",
  },
  {
    id: "restore-grid",
    name: "Restore Grid",
    family: "restore",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["A", "P", "R", "*"],
    description: "Your panels remember they were whole.",
    summon: "repair",
    inspiredByFamily: "repair",
  },

  // —— Chrono / rain / mine / seek / remote / lock ——
  {
    id: "chrono-seed",
    name: "Chrono Seed",
    family: "chrono",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 16,
    codes: ["C", "K", "Z"],
    description: "A ticking orb of slowed light in the enemy area.",
    summon: "chrono",
    inspiredByFamily: "timebomb",
  },
  {
    id: "chrono-seed-2",
    name: "Chrono Seed 2",
    family: "chrono",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 120,
    mb: 22,
    codes: ["C", "L", "Y"],
    description: "Louder tick. Bigger bloom.",
    summon: "chrono",
    inspiredByFamily: "timebomb",
  },
  {
    id: "chrono-seed-3",
    name: "Chrono Seed 3",
    family: "chrono",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 160,
    mb: 28,
    codes: ["C", "M", "X"],
    description: "When it blooms, time looks briefly inverted.",
    summon: "chrono",
    inspiredByFamily: "timebomb",
  },
  {
    id: "rain-veil",
    name: "Rain Veil",
    family: "rainveil",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 60,
    mb: 14,
    codes: ["A", "C", "G"],
    description: "Rain walks one column, up and down.",
    summon: "rain",
    inspiredByFamily: "cloud",
  },
  {
    id: "rain-veil-2",
    name: "Rain Veil 2",
    family: "rainveil",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 80,
    mb: 20,
    codes: ["B", "D", "H"],
    description: "Heavier rain-light.",
    summon: "rain",
    inspiredByFamily: "cloud",
  },
  {
    id: "rain-veil-3",
    name: "Rain Veil 3",
    family: "rainveil",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: 100,
    mb: 26,
    codes: ["C", "E", "I"],
    description: "A column of storm-glass.",
    summon: "rain",
    inspiredByFamily: "cloud",
  },
  {
    id: "hidden-spark",
    name: "Hidden Spark",
    family: "hiddenspark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 160,
    mb: 16,
    codes: ["H", "M", "N"],
    description: "A mine of folded lightning on an enemy tile.",
    summon: "mine",
    inspiredByFamily: "mine",
  },
  {
    id: "hidden-spark-2",
    name: "Hidden Spark 2",
    family: "hiddenspark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 180,
    mb: 20,
    codes: ["H", "O", "P"],
    description: "Hotter mine.",
    summon: "mine",
    inspiredByFamily: "mine",
  },
  {
    id: "hidden-spark-3",
    name: "Hidden Spark 3",
    family: "hiddenspark",
    class: "standard",
    element: "volt",
    tactic: "none",
    power: 200,
    mb: 24,
    codes: ["H", "Q", "R"],
    description: "The tile looks empty until it isn't.",
    summon: "mine",
    inspiredByFamily: "mine",
  },
  {
    id: "seek-charge",
    name: "Seek Charge",
    family: "seekcharge",
    class: "standard",
    element: "ember",
    tactic: "mark",
    power: 100,
    mb: 16,
    codes: ["D", "K", "N"],
    description: "Looks right, then detonates on the first body it finds.",
    summon: "seek",
    inspiredByFamily: "dynamite",
  },
  {
    id: "seek-charge-2",
    name: "Seek Charge 2",
    family: "seekcharge",
    class: "standard",
    element: "ember",
    tactic: "mark",
    power: 120,
    mb: 20,
    codes: ["D", "L", "O"],
    description: "Looks diagonally.",
    summon: "seek",
    inspiredByFamily: "dynamite",
  },
  {
    id: "seek-charge-3",
    name: "Seek Charge 3",
    family: "seekcharge",
    class: "standard",
    element: "ember",
    tactic: "mark",
    power: 150,
    mb: 24,
    codes: ["D", "M", "P"],
    description: "Looks up and down the column.",
    summon: "seek",
    inspiredByFamily: "dynamite",
  },
  {
    id: "remote-geist",
    name: "Remote Geist",
    family: "remotegeist",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 14,
    codes: ["E", "N", "R"],
    description: "A steerable fist of mist. You aim it after it appears.",
    summon: "remote",
    inspiredByFamily: "remobit",
  },
  {
    id: "remote-geist-2",
    name: "Remote Geist 2",
    family: "remotegeist",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 100,
    mb: 20,
    codes: ["F", "O", "S"],
    description: "Faster remote fist.",
    summon: "remote",
    inspiredByFamily: "remobit",
  },
  {
    id: "remote-geist-3",
    name: "Remote Geist 3",
    family: "remotegeist",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 120,
    mb: 26,
    codes: ["G", "P", "T"],
    description: "A heavy remote smash.",
    summon: "remote",
    inspiredByFamily: "remobit",
  },
  {
    id: "trace-satellite",
    name: "Trace Satellite",
    family: "tracesat",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 10,
    mb: 10,
    codes: ["L", "O", "S"],
    description: "A tiny orbiting shard that auto-fires.",
    summon: "lockon",
    inspiredByFamily: "lockon",
  },
  {
    id: "trace-satellite-2",
    name: "Trace Satellite 2",
    family: "tracesat",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 15,
    mb: 16,
    codes: ["L", "P", "T"],
    description: "Sharper satellite.",
    summon: "lockon",
    inspiredByFamily: "lockon",
  },
  {
    id: "trace-satellite-3",
    name: "Trace Satellite 3",
    family: "tracesat",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 20,
    mb: 22,
    codes: ["L", "Q", "U"],
    description: "A bright lock-on moonlet.",
    summon: "lockon",
    inspiredByFamily: "lockon",
  },

  // —— Wick / wither / solid ——
  {
    id: "life-wick",
    name: "Life Wick",
    family: "lifewick",
    class: "standard",
    element: "void",
    tactic: "summon",
    power: null,
    mb: 12,
    codes: ["C", "N", "P"],
    description: "A candle of pale fire. Ticks HP until snuffed.",
    summon: "wick",
    inspiredByFamily: "candle",
  },
  {
    id: "life-wick-2",
    name: "Life Wick 2",
    family: "lifewick",
    class: "standard",
    element: "void",
    tactic: "summon",
    power: null,
    mb: 18,
    codes: ["C", "O", "Q"],
    description: "Longer wick.",
    summon: "wick",
    inspiredByFamily: "candle",
  },
  {
    id: "life-wick-3",
    name: "Life Wick 3",
    family: "lifewick",
    class: "standard",
    element: "void",
    tactic: "summon",
    power: null,
    mb: 24,
    codes: ["C", "P", "R"],
    description: "A stubborn flame.",
    summon: "wick",
    inspiredByFamily: "candle",
  },
  {
    id: "wither-idol",
    name: "Wither Idol",
    family: "wither",
    class: "standard",
    element: "void",
    tactic: "summon",
    power: null,
    mb: 26,
    codes: ["A", "N", "U"],
    description: "A kneeling statue of smoke-glass. Enemy HP ticks down.",
    summon: "idol",
    inspiredByFamily: "anubis",
  },
  {
    id: "frost-cube",
    name: "Frost Cube",
    family: "solid",
    class: "standard",
    element: "tide",
    tactic: "summon",
    power: null,
    mb: 8,
    codes: ["A", "C", "I"],
    description: "An ice obstacle of translucent mass. Melts if struck by ember.",
    summon: "cube",
    inspiredByFamily: "cube",
  },
  {
    id: "stone-cube",
    name: "Stone Cube",
    family: "solid",
    class: "standard",
    element: "void",
    tactic: "summon",
    power: null,
    mb: 10,
    codes: ["A", "C", "R", "*"],
    description: "Three rock-ghosts scatter onto random tiles.",
    summon: "cube",
    inspiredByFamily: "cube",
  },

  // —— Buster weave / tempo / fade / stoneshape / nullveil ——
  {
    id: "buster-guard",
    name: "Buster Guard",
    family: "busterweave",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["A", "C", "G"],
    description: "One Custom turn: the charge button raises Met Veil.",
    summon: "buster",
    inspiredByFamily: "buster-mod",
  },
  {
    id: "buster-seed",
    name: "Buster Seed",
    family: "busterweave",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["B", "N", "T"],
    description: "One Custom turn: the charge button throws Ember Seed.",
    summon: "buster",
    inspiredByFamily: "buster-mod",
  },
  {
    id: "buster-blade",
    name: "Buster Blade",
    family: "busterweave",
    class: "standard",
    element: "void",
    tactic: "blade",
    power: null,
    mb: 8,
    codes: ["H", "L", "S"],
    description: "One Custom turn: the charge button swings Phantom Edge.",
    summon: "buster",
    inspiredByFamily: "buster-mod",
  },
  {
    id: "buster-fist",
    name: "Buster Fist",
    family: "busterweave",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: null,
    mb: 8,
    codes: ["G", "P", "T"],
    description: "One Custom turn: the charge button throws Geist Fist.",
    summon: "buster",
    inspiredByFamily: "buster-mod",
  },
  {
    id: "slow-tempo",
    name: "Slow Tempo",
    family: "tempo",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 10,
    codes: ["A", "Q", "S"],
    description: "The Custom Gauge thickens. Both sides wait longer.",
    summon: "gauge",
    inspiredByFamily: "gauge",
  },
  {
    id: "fast-tempo",
    name: "Fast Tempo",
    family: "tempo",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 10,
    codes: ["A", "E", "F"],
    description: "The Custom Gauge races. Hands refill sooner.",
    summon: "gauge",
    inspiredByFamily: "gauge",
  },
  {
    id: "fade-1",
    name: "Fade 1",
    family: "fade",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["I", "J", "K"],
    description: "Brief immunity. The body becomes afterimage.",
    summon: "fade",
    inspiredByFamily: "invis",
  },
  {
    id: "fade-2",
    name: "Fade 2",
    family: "fade",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 14,
    codes: ["I", "L", "M"],
    description: "Longer fade.",
    summon: "fade",
    inspiredByFamily: "invis",
  },
  {
    id: "fade-3",
    name: "Fade 3",
    family: "fade",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 20,
    codes: ["I", "N", "O"],
    description: "A long walk as smoke.",
    summon: "fade",
    inspiredByFamily: "invis",
  },
  {
    id: "drop-veil",
    name: "Drop Veil",
    family: "fade",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 12,
    codes: ["A", "D", "L"],
    description: "Invisible until you attack.",
    summon: "fade",
    inspiredByFamily: "invis",
  },
  {
    id: "rise-veil",
    name: "Rise Veil",
    family: "fade",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 12,
    codes: ["B", "E", "R"],
    description: "Invisible while idle; visible only in the swing.",
    summon: "fade",
    inspiredByFamily: "invis",
  },
  {
    id: "stone-shape",
    name: "Stone Shape",
    family: "stoneshape",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 18,
    codes: ["I", "R", "S"],
    description: "Defense up, rooted. The body looks carved from smoke-marble.",
    summon: "shield",
    inspiredByFamily: "ironbody",
  },
  {
    id: "null-veil",
    name: "Null Veil",
    family: "nullveil",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 8,
    codes: ["A", "F", "R", "*"],
    description: "A bubble of nothing. Nullifies one hit.",
    summon: "shield",
    inspiredByFamily: "barrier",
  },
  {
    id: "tide-wrap",
    name: "Tide Wrap",
    family: "nullveil",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: null,
    mb: 14,
    codes: ["A", "Q", "W"],
    description: "Aqua wall that reforms after a chip of damage.",
    summon: "wrap",
    inspiredByFamily: "barrier",
  },
  {
    id: "grove-convert",
    name: "Grove Convert",
    family: "nullveil",
    class: "standard",
    element: "grove",
    tactic: "mend",
    power: null,
    mb: 16,
    codes: ["G", "L", "S"],
    description: "The next hit becomes HP instead of a wound.",
    summon: "wrap",
    inspiredByFamily: "barrier",
  },
  {
    id: "tide-aura",
    name: "Tide Aura",
    family: "nullveil",
    class: "standard",
    element: "tide",
    tactic: "none",
    power: null,
    mb: 14,
    codes: ["A", "D", "K"],
    description: "Ignore hits under 10. Weak to volt.",
    summon: "aura",
    inspiredByFamily: "barrier",
  },
  {
    id: "ember-aura",
    name: "Ember Aura",
    family: "nullveil",
    class: "standard",
    element: "ember",
    tactic: "none",
    power: null,
    mb: 18,
    codes: ["F", "I", "R"],
    description: "Ignore hits under 40. Weak to tide.",
    summon: "aura",
    inspiredByFamily: "barrier",
  },
  {
    id: "grove-aura",
    name: "Grove Aura",
    family: "nullveil",
    class: "standard",
    element: "grove",
    tactic: "none",
    power: null,
    mb: 22,
    codes: ["G", "R", "W"],
    description: "Ignore hits under 80. Weak to ember.",
    summon: "aura",
    inspiredByFamily: "barrier",
  },
  {
    id: "life-aura",
    name: "Life Aura",
    family: "nullveil",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 28,
    codes: ["D", "H", "U"],
    description: "Ignore all hits under 100.",
    summon: "aura",
    inspiredByFamily: "barrier",
  },

  // —— Later-game remixes ——
  {
    id: "needle-burst",
    name: "Needle Burst",
    family: "needleburst",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 10,
    mb: 5,
    codes: ["B", "D", "S", "*"],
    description: "A ghost machine-gun. Many small needles, no weight.",
    summon: "spreader",
    inspiredByFamily: "vulcan",
  },
  {
    id: "needle-burst-2",
    name: "Needle Burst 2",
    family: "needleburst",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 15,
    mb: 18,
    codes: ["D", "F", "L"],
    description: "Denser needle rain.",
    summon: "spreader",
    inspiredByFamily: "vulcan",
  },
  {
    id: "needle-burst-3",
    name: "Needle Burst 3",
    family: "needleburst",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 20,
    mb: 30,
    codes: ["A", "G", "R"],
    description: "A veil of needles.",
    summon: "spreader",
    inspiredByFamily: "vulcan",
  },
  {
    id: "aether-sail",
    name: "Aether Sail",
    family: "aethersail",
    class: "standard",
    element: "void",
    tactic: "gale",
    power: 20,
    mb: 4,
    codes: ["*"],
    description: "A puff of wind-light that shoves the target back a panel.",
    summon: "spreader",
    inspiredByFamily: "airshot",
  },
  {
    id: "siege-pulse",
    name: "Siege Pulse",
    family: "siegepulse",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 140,
    mb: 28,
    codes: ["A", "G", "R"],
    description: "Tank-cannon of stacked rings. Splash on the hit tile.",
    summon: "cannon",
    inspiredByFamily: "tankcannon",
  },
  {
    id: "counter-hymn",
    name: "Counter Hymn",
    family: "counterhymn",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 20,
    codes: ["A", "N", "T"],
    description: "If the next enemy summon matches your last element, it rebounds.",
    summon: "silence",
    inspiredByFamily: "anti",
  },

  // —— Original new families ——
  {
    id: "prism-lance",
    name: "Prism Lance",
    family: "prism",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 90,
    mb: 18,
    codes: ["P", "R", "S"],
    description: "A spear of split light. Hits the locked panel and two adjacent hues.",
    summon: "prism",
    inspiredByFamily: "arrow",
    summonNote: "Original Anima data — refraction, not a BN chip.",
  },
  {
    id: "gravity-well",
    name: "Gravity Well",
    family: "gravity",
    class: "standard",
    element: "void",
    tactic: "shatter",
    power: 70,
    mb: 22,
    codes: ["G", "V", "W"],
    description: "A dim star on a panel. Viruses slide toward it, then the well collapses.",
    summon: "gravity",
    inspiredByFamily: "gaia",
    summonNote: "Original Anima data.",
  },
  {
    id: "echo-fold",
    name: "Echo Fold",
    family: "echo-fold",
    class: "standard",
    element: "void",
    tactic: "none",
    power: null,
    mb: 16,
    codes: ["E", "F", "O"],
    description: "Replays the last summoned fragment as a fainter ghost (half power).",
    summon: "rift",
    inspiredByFamily: "interrupt",
    summonNote: "Original Anima data.",
  },
  {
    id: "star-vein",
    name: "Star Vein",
    family: "star-vein",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 40,
    mb: 20,
    codes: ["S", "T", "V"],
    description: "Constellation lock-on. Lines draw between viruses, then snap.",
    summon: "lockon",
    inspiredByFamily: "lockon",
    summonNote: "Original Anima data.",
  },
  {
    id: "rift-needle",
    name: "Rift Needle",
    family: "rift",
    class: "standard",
    element: "void",
    tactic: "mark",
    power: 110,
    mb: 18,
    codes: ["N", "R", "Z"],
    description: "A cursor-shot that ignores invisibility. The needle is a slit in the air.",
    summon: "rift",
    inspiredByFamily: "lockon",
    summonNote: "Original Anima data.",
  },
  {
    id: "dreamstitch",
    name: "Dreamstitch",
    family: "dreamstitch",
    class: "standard",
    element: "void",
    tactic: "none",
    power: 80,
    mb: 24,
    codes: ["D", "M", "Y"],
    description: "Weaves your last two elements into one hybrid pulse.",
    summon: "prism",
    inspiredByFamily: "cannon",
    summonNote: "Original Anima data.",
  },

  // —— Apex sigils (Navi-inspired, original names) ——
  {
    id: "mendlight-sigil",
    name: "Mendlight Sigil",
    family: "apex-sigil",
    class: "apex",
    element: "void",
    tactic: "mend",
    power: 80,
    mb: 40,
    codes: ["R"],
    description: "A healer-outline appears, fires a merciful shot, then mends you.",
    summon: "sigil",
    inspiredByFamily: "navi",
  },
  {
    id: "shock-titan-sigil",
    name: "Shock Titan Sigil",
    family: "apex-sigil",
    class: "apex",
    element: "void",
    tactic: "shatter",
    power: 100,
    mb: 44,
    codes: ["G"],
    description: "A giant of cracked light stomps; the enemy area spiderwebs.",
    summon: "sigil",
    inspiredByFamily: "navi",
  },
  {
    id: "column-slash-sigil",
    name: "Column Slash Sigil",
    family: "apex-sigil",
    class: "apex",
    element: "void",
    tactic: "blade",
    power: 160,
    mb: 48,
    codes: ["B"],
    description: "A visored duelist of gold-glass cuts the nearest enemy column.",
    summon: "sigil",
    inspiredByFamily: "navi",
  },
  {
    id: "cinder-arm-sigil",
    name: "Cinder Arm Sigil",
    family: "apex-sigil",
    class: "apex",
    element: "ember",
    tactic: "none",
    power: 140,
    mb: 42,
    codes: ["F"],
    description: "A fire-outline extends one row as a burning arm.",
    summon: "sigil",
    inspiredByFamily: "navi",
  },
  {
    id: "storm-pin-sigil",
    name: "Storm Pin Sigil",
    family: "apex-sigil",
    class: "apex",
    element: "volt",
    tactic: "none",
    power: 150,
    mb: 46,
    codes: ["E"],
    description: "Lightning writes itself onto the enemy's current panel.",
    summon: "sigil",
    inspiredByFamily: "navi",
  },

  // —— Nova (Giga-inspired, original) ——
  {
    id: "area-bloom",
    name: "Area Bloom",
    family: "nova",
    class: "nova",
    element: "void",
    tactic: "none",
    power: 200,
    mb: 95,
    codes: ["X"],
    description: "The whole enemy field detonates as pale fire. One Nova per folder.",
    summon: "gaia",
    inspiredByFamily: "giga-bn6",
  },
  {
    id: "delta-veil",
    name: "Delta Veil",
    family: "nova",
    class: "nova",
    element: "void",
    tactic: "blade",
    power: 260,
    mb: 82,
    codes: ["Z"],
    description: "Three overlapping phantom cuts in a triangle of light.",
    summon: "sword",
    inspiredByFamily: "giga-bn6",
  },
  {
    id: "hub-chorus",
    name: "Hub Chorus",
    family: "nova",
    class: "nova",
    element: "void",
    tactic: "none",
    power: null,
    mb: 99,
    codes: ["J"],
    description: "Every standard fragment in the next hand plays itself, faintly, at once.",
    summon: "rift",
    inspiredByFamily: "giga-bn6",
  },
]);

/** @type {Record<string, EnergyFragment>} */
export const FRAGMENT_BY_ID = Object.fromEntries(ENERGY_FRAGMENTS.map((f) => [f.id, f]));

/** @param {string} id */
export function getFragment(id) {
  return FRAGMENT_BY_ID[id] || null;
}

/** @param {string} family */
export function fragmentsByFamily(family) {
  return ENERGY_FRAGMENTS.filter((f) => f.family === family);
}

/** @param {string} klass */
export function fragmentsByClass(klass) {
  return ENERGY_FRAGMENTS.filter((f) => f.class === klass);
}
