// @ts-check
/**
 * Attainable character-inventory catalog — original Anima Protocol names.
 *
 * Freeform Inventory entities have no master list in the store. This catalog
 * is the steward-only bag of gear / weapon / armor / consumable / artifact /
 * misc the Protocol already treats as attainable. Do not reuse Capcom chip
 * names. Combat Folders stay Echo Keys (30 slots).
 */

/** @typedef {"gear" | "weapon" | "armor" | "consumable" | "artifact" | "misc"} InventoryType */
/** @typedef {"common" | "uncommon" | "rare" | "legendary"} InventoryRarity */
/** @typedef {"head" | "chest" | "hands" | "feet" | "weapon" | "offhand" | "accessory" | "none"} InventorySlot */

/**
 * @typedef {object} AttainableItem
 * @property {string} id
 * @property {string} name
 * @property {InventoryType} type
 * @property {InventoryRarity} rarity
 * @property {InventorySlot} slot
 * @property {string} description
 * @property {Record<string, number>} [stat_modifiers]
 * @property {string[]} [effects]
 * @property {number} [trade_value]
 * @property {string[]} [narrative_triggers]
 */

/**
 * @param {AttainableItem} row
 * @returns {AttainableItem}
 */
function item(row) {
  return {
    trade_value: row.trade_value ?? 10,
    stat_modifiers: row.stat_modifiers || {},
    effects: row.effects || [],
    narrative_triggers: row.narrative_triggers || [],
    ...row,
  };
}

/** @type {AttainableItem[]} */
export const ATTAINABLE_ITEMS = [
  // —— Weapons ——
  item({
    id: "pulse-brand",
    name: "Pulse Brand",
    type: "weapon",
    rarity: "common",
    slot: "weapon",
    description: "A short glass-steel edge that hums when the Lattice is near.",
    stat_modifiers: { strength: 2 },
    effects: ["light_projection"],
    trade_value: 18,
  }),
  item({
    id: "phantom-cleaver",
    name: "Phantom Cleaver",
    type: "weapon",
    rarity: "uncommon",
    slot: "weapon",
    description: "Horizon-cut blade. Leaves an afterimage instead of a wound-sound.",
    stat_modifiers: { strength: 3, dexterity: 1 },
    effects: ["afterimage_cut"],
    trade_value: 36,
  }),
  item({
    id: "lattice-rapier",
    name: "Lattice Rapier",
    type: "weapon",
    rarity: "rare",
    slot: "weapon",
    description: "Needle of coherent light. Finds the seam in a veil.",
    stat_modifiers: { dexterity: 4, intelligence: 2 },
    effects: ["veil_pierce"],
    trade_value: 72,
    narrative_triggers: ["unlock_path"],
  }),
  item({
    id: "choir-halberd",
    name: "Choir Halberd",
    type: "weapon",
    rarity: "rare",
    slot: "weapon",
    description: "Polearm that rings a fifth when it meets resistance.",
    stat_modifiers: { strength: 4, charisma: 2 },
    effects: ["harmonic_shock"],
    trade_value: 80,
  }),
  item({
    id: "serenity-edge",
    name: "Serenity Edge",
    type: "weapon",
    rarity: "legendary",
    slot: "weapon",
    description: "Remembrance given a cutting instruction. Will not strike the unwilling.",
    stat_modifiers: { strength: 5, wisdom: 4, charisma: 3 },
    effects: ["witness_strike", "undead_slayer"],
    trade_value: 160,
    narrative_triggers: ["confront_shadow_self", "ultimate_battle"],
  }),
  item({
    id: "echo-glaive",
    name: "Echo Glaive",
    type: "weapon",
    rarity: "uncommon",
    slot: "weapon",
    description: "Wide crescent that remembers the last motion and repeats it once.",
    stat_modifiers: { strength: 3 },
    effects: ["echo_follow"],
    trade_value: 40,
  }),
  item({
    id: "veil-dagger",
    name: "Veil Dagger",
    type: "weapon",
    rarity: "common",
    slot: "weapon",
    description: "Palm-length fade-steel. Better at opening doors than throats.",
    stat_modifiers: { dexterity: 2 },
    effects: ["quiet_cut"],
    trade_value: 14,
  }),
  item({
    id: "prime-resonance-blade",
    name: "Prime Resonance Blade",
    type: "weapon",
    rarity: "legendary",
    slot: "weapon",
    description: "A steward's working edge. Holds a Prime instruction without becoming one.",
    stat_modifiers: { strength: 5, intelligence: 3 },
    effects: ["prime_attune"],
    trade_value: 180,
    narrative_triggers: ["reveal_secret"],
  }),

  // —— Armor ——
  item({
    id: "aether-weave-tunic",
    name: "Aether-Weave Tunic",
    type: "armor",
    rarity: "common",
    slot: "chest",
    description: "Thread that drinks stray pulse and returns it as warmth.",
    stat_modifiers: { constitution: 2 },
    effects: ["pulse_dampen"],
    trade_value: 16,
  }),
  item({
    id: "nullveil-mail",
    name: "Nullveil Mail",
    type: "armor",
    rarity: "uncommon",
    slot: "chest",
    description: "Overlapping glass scales. One hit becomes a shimmer, then gone.",
    stat_modifiers: { constitution: 3, dexterity: 1 },
    effects: ["nullify_once"],
    trade_value: 42,
  }),
  item({
    id: "grove-plate",
    name: "Grove Plate",
    type: "armor",
    rarity: "rare",
    slot: "chest",
    description: "Living bark-steel. Mends hairline cracks overnight.",
    stat_modifiers: { constitution: 4, wisdom: 2 },
    effects: ["slow_mend", "poison_immunity"],
    trade_value: 78,
  }),
  item({
    id: "sovereign-carapace",
    name: "Sovereign Carapace",
    type: "armor",
    rarity: "legendary",
    slot: "chest",
    description: "Choir-forged shell. Remembers every blow and redistributes the next.",
    stat_modifiers: { constitution: 5, charisma: 2 },
    effects: ["choir_guard", "fire_resistance"],
    trade_value: 150,
  }),
  item({
    id: "mend-circlet",
    name: "Mend Circlet",
    type: "armor",
    rarity: "common",
    slot: "head",
    description: "Thin ring that cools a headache and steadies a shaky hand.",
    stat_modifiers: { wisdom: 1 },
    effects: ["calm_focus"],
    trade_value: 12,
  }),
  item({
    id: "tide-greaves",
    name: "Tide Greaves",
    type: "armor",
    rarity: "uncommon",
    slot: "feet",
    description: "Walk as if the floor were still water. No splash.",
    stat_modifiers: { dexterity: 2, constitution: 1 },
    effects: ["quiet_step"],
    trade_value: 28,
  }),
  item({
    id: "volt-gauntlets",
    name: "Volt Gauntlets",
    type: "armor",
    rarity: "rare",
    slot: "hands",
    description: "Catch a spark and keep it until you decide where it goes.",
    stat_modifiers: { strength: 2, intelligence: 3 },
    effects: ["hold_charge"],
    trade_value: 64,
  }),
  item({
    id: "crown-of-coherence",
    name: "Crown of Coherence",
    type: "armor",
    rarity: "legendary",
    slot: "head",
    description: "Not a throne. A reminder that the Lattice can still agree with itself.",
    stat_modifiers: { wisdom: 5, intelligence: 3, charisma: 2 },
    effects: ["dark_vision", "coherence_aura"],
    trade_value: 170,
    narrative_triggers: ["reveal_secret"],
  }),

  // —— Gear ——
  item({
    id: "resonance-tuner",
    name: "Resonance Tuner",
    type: "gear",
    rarity: "common",
    slot: "accessory",
    description: "Pocket fork. Tells you when a room is lying about its silence.",
    stat_modifiers: { wisdom: 1 },
    effects: ["attune_hint"],
    trade_value: 15,
  }),
  item({
    id: "field-attuner",
    name: "Field Attuner",
    type: "gear",
    rarity: "uncommon",
    slot: "accessory",
    description: "Clip-on coil that leans a local field toward Grove or Tide.",
    stat_modifiers: { intelligence: 2 },
    effects: ["field_bias"],
    trade_value: 34,
  }),
  item({
    id: "lattice-compass",
    name: "Lattice Compass",
    type: "gear",
    rarity: "rare",
    slot: "accessory",
    description: "Needle that points at coherence, not north.",
    stat_modifiers: { wisdom: 3, intelligence: 1 },
    effects: ["find_seam"],
    trade_value: 70,
    narrative_triggers: ["unlock_path"],
  }),
  item({
    id: "prime-focus-ring",
    name: "Prime Focus Ring",
    type: "gear",
    rarity: "legendary",
    slot: "accessory",
    description: "A ring that will not sit on a hand that treats the Lattice as a toy.",
    stat_modifiers: { intelligence: 4, wisdom: 3 },
    effects: ["prime_focus"],
    trade_value: 140,
  }),
  item({
    id: "echo-satchel",
    name: "Echo Satchel",
    type: "gear",
    rarity: "common",
    slot: "none",
    description: "Lined with fade-cloth. Small things stay small until you need them.",
    effects: ["light_carry"],
    trade_value: 10,
  }),
  item({
    id: "fold-lantern",
    name: "Fold Lantern",
    type: "gear",
    rarity: "uncommon",
    slot: "offhand",
    description: "Light that folds into a coin. Unfolds without a spark.",
    effects: ["fold_light"],
    trade_value: 26,
  }),
  item({
    id: "choir-bell",
    name: "Choir Bell",
    type: "gear",
    rarity: "rare",
    slot: "accessory",
    description: "One clean tone. Companions in range remember why they came.",
    stat_modifiers: { charisma: 3 },
    effects: ["rally_tone"],
    trade_value: 68,
  }),
  item({
    id: "wheel-crown-clasp",
    name: "Wheel-Crown Clasp",
    type: "gear",
    rarity: "legendary",
    slot: "accessory",
    description: "Cloak clasp cut like a binary sigil. Holds a coat and a vow.",
    stat_modifiers: { charisma: 4, wisdom: 2 },
    effects: ["sigil_bind"],
    trade_value: 130,
    narrative_triggers: ["confront_shadow_self"],
  }),

  // —— Consumables ——
  item({
    id: "mend-vial",
    name: "Mend Vial",
    type: "consumable",
    rarity: "common",
    slot: "none",
    description: "Clear draught. Closes a cut the way a conversation closes a wound.",
    effects: ["mend_small"],
    trade_value: 8,
  }),
  item({
    id: "tide-flask",
    name: "Tide Flask",
    type: "consumable",
    rarity: "uncommon",
    slot: "none",
    description: "Cold water that remembers rain. Cools ember and temper alike.",
    effects: ["quench", "mend_modest"],
    trade_value: 18,
  }),
  item({
    id: "ember-draught",
    name: "Ember Draught",
    type: "consumable",
    rarity: "rare",
    slot: "none",
    description: "Last warmth of a hearth. One swallow, then the night is less certain.",
    stat_modifiers: { strength: 2 },
    effects: ["ember_surge"],
    trade_value: 40,
  }),
  item({
    id: "prime-elixir",
    name: "Prime Elixir",
    type: "consumable",
    rarity: "legendary",
    slot: "none",
    description: "A single measure of coherence. Do not drink it to forget.",
    effects: ["full_mend", "clarity"],
    trade_value: 90,
    narrative_triggers: ["ultimate_battle"],
  }),
  item({
    id: "veil-salve",
    name: "Veil Salve",
    type: "consumable",
    rarity: "common",
    slot: "none",
    description: "Smear on a bruise or a door-seam. Both become less obvious.",
    effects: ["fade_mark"],
    trade_value: 7,
  }),
  item({
    id: "volt-spark-ampoule",
    name: "Volt-Spark Ampoule",
    type: "consumable",
    rarity: "uncommon",
    slot: "none",
    description: "Break underfoot. The next step carries a sting.",
    effects: ["volt_step"],
    trade_value: 20,
  }),
  item({
    id: "grove-seedcake",
    name: "Grove Seedcake",
    type: "consumable",
    rarity: "rare",
    slot: "none",
    description: "Dense, green, a little sweet. The body remembers it was once a garden.",
    effects: ["grove_restore", "poison_cleanse"],
    trade_value: 36,
  }),
  item({
    id: "fifth-tone-nectar",
    name: "Fifth-Tone Nectar",
    type: "consumable",
    rarity: "legendary",
    slot: "none",
    description: "A sip that makes five voices agree for one breath.",
    stat_modifiers: { charisma: 3, wisdom: 2 },
    effects: ["fifth_tone"],
    trade_value: 95,
  }),

  // —— Artifacts ——
  item({
    id: "memory-shard-lens",
    name: "Memory-Shard Lens",
    type: "artifact",
    rarity: "common",
    slot: "accessory",
    description: "Look through it and yesterday's room is still furnished.",
    effects: ["recall_room"],
    trade_value: 22,
  }),
  item({
    id: "beth-home-token",
    name: "Beth Home Token",
    type: "artifact",
    rarity: "uncommon",
    slot: "accessory",
    description: "A coin that warms when you are allowed to stay.",
    stat_modifiers: { wisdom: 2 },
    effects: ["home_sense"],
    trade_value: 44,
    narrative_triggers: ["unlock_path"],
  }),
  item({
    id: "lamed-vigil-seal",
    name: "Lamed Vigil Seal",
    type: "artifact",
    rarity: "rare",
    slot: "accessory",
    description: "Wax that will not cool while someone is keeping watch.",
    stat_modifiers: { constitution: 2, wisdom: 3 },
    effects: ["vigil"],
    trade_value: 76,
  }),
  item({
    id: "censer-of-quiet",
    name: "Censer of Quiet",
    type: "artifact",
    rarity: "common",
    slot: "offhand",
    description: "Smoke that asks a room to lower its voice.",
    effects: ["soften_room"],
    trade_value: 20,
  }),
  item({
    id: "saltloop-charm",
    name: "Saltloop Charm",
    type: "artifact",
    rarity: "uncommon",
    slot: "accessory",
    description: "A ring of salt that never spills. Circles hold.",
    effects: ["ward_circle"],
    trade_value: 38,
  }),
  item({
    id: "tet-commons-mark",
    name: "Tet Commons Mark",
    type: "artifact",
    rarity: "rare",
    slot: "accessory",
    description: "Stamp of a shared table. Trade goes easier when it is shown.",
    stat_modifiers: { charisma: 3 },
    effects: ["fair_trade"],
    trade_value: 66,
  }),
  item({
    id: "wheel-and-crown-medal",
    name: "Wheel-and-Crown Medal",
    type: "artifact",
    rarity: "legendary",
    slot: "accessory",
    description: "Binary sigil struck in quiet metal. Proof the Protocol still has a steward.",
    stat_modifiers: { charisma: 4, wisdom: 4 },
    effects: ["steward_mark"],
    trade_value: 200,
    narrative_triggers: ["reveal_secret", "ultimate_battle"],
  }),
  item({
    id: "final-sigil-replica",
    name: "Final Sigil Replica",
    type: "artifact",
    rarity: "legendary",
    slot: "none",
    description: "A study copy. It will not end a world. It will remind you how one almost did.",
    stat_modifiers: { intelligence: 5, wisdom: 2 },
    effects: ["sigil_study"],
    trade_value: 190,
    narrative_triggers: ["confront_shadow_self"],
  }),

  // —— Misc ——
  item({
    id: "folded-thread",
    name: "Folded Thread",
    type: "misc",
    rarity: "common",
    slot: "none",
    description: "A length of fade-thread. Ties a seam or a promise.",
    trade_value: 4,
  }),
  item({
    id: "lattice-dust",
    name: "Lattice Dust",
    type: "misc",
    rarity: "uncommon",
    slot: "none",
    description: "Fine grit that sparkles only when you stop looking directly.",
    trade_value: 12,
  }),
  item({
    id: "resonance-ink",
    name: "Resonance Ink",
    type: "misc",
    rarity: "rare",
    slot: "none",
    description: "Writes a line that other Animas can still hear tomorrow.",
    trade_value: 30,
    narrative_triggers: ["reveal_secret"],
  }),
  item({
    id: "spare-panel-chalk",
    name: "Spare-Panel Chalk",
    type: "misc",
    rarity: "common",
    slot: "none",
    description: "Marks a cracked floor so no one steps through.",
    trade_value: 3,
  }),
  item({
    id: "echo-key-ribbon",
    name: "Echo Key Ribbon",
    type: "misc",
    rarity: "uncommon",
    slot: "none",
    description: "Ties a Resonance Array closed. Not a Key. A courtesy.",
    trade_value: 11,
  }),
  item({
    id: "slipthk-page-fragment",
    name: "Slipthk Page Fragment",
    type: "misc",
    rarity: "rare",
    slot: "none",
    description: "A torn continuum leaf. The sentence continues on the other side of sleep.",
    trade_value: 48,
    narrative_triggers: ["unlock_path"],
  }),
  item({
    id: "anima-protocol-seal",
    name: "Anima Protocol Seal",
    type: "misc",
    rarity: "legendary",
    slot: "none",
    description: "Wax and light. Marks a document as spoken in the steward's name.",
    trade_value: 120,
  }),
  item({
    id: "steward-ledger",
    name: "Steward Ledger",
    type: "misc",
    rarity: "legendary",
    slot: "none",
    description: "A thin book that lists what the Protocol has already given, so it is not given twice.",
    stat_modifiers: { intelligence: 2, wisdom: 2 },
    effects: ["catalog_memory"],
    trade_value: 110,
  }),
];

/** @type {Record<string, AttainableItem>} */
export const ATTAINABLE_ITEM_BY_ID = Object.fromEntries(
  ATTAINABLE_ITEMS.map((row) => [row.id, row]),
);

export const ATTAINABLE_ITEM_IDS = ATTAINABLE_ITEMS.map((row) => row.id);

/** How many Inventory rows to request when checking a bag. */
export const INVENTORY_LIST_LIMIT = 500;

export function catalogItemIds() {
  return ATTAINABLE_ITEM_IDS;
}
